# Setting Everything Up

In [1]:
import pandas as pd
from datetime import datetime

In [2]:
#import the file from the web
import requests
from bs4 import BeautifulSoup
import pandas as pd
from unicodedata import normalize
import re
from datetime import datetime
from pandas import read_csv 
from sklearn.feature_extraction.text import CountVectorizer
import json
from flatten_json import flatten


# I can give a number or use None to remove maximum ceiling & display all columns
pd.options.display.max_columns = None

# # I want to be able to see the entire narrative, so remove the maximum width for each column
# pd.options.display.max_colwidth = None

# pd.options.display.float_format = '{:,.0f}'.format

import string

%matplotlib inline

In [3]:
%load_ext rpy2.ipython
%load_ext autoreload
%autoreload 2

%matplotlib inline  
from matplotlib import rcParams
rcParams['figure.figsize'] = (8, 8)

import warnings
from rpy2.rinterface import RRuntimeWarning
warnings.filterwarnings("ignore") # Ignore all warnings
# warnings.filterwarnings("ignore", category=RRuntimeWarning) # Show some warnings

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import display, HTML

In [4]:
%%javascript
// Disable auto-scrolling
IPython.OutputArea.prototype._should_scroll = function(lines) {
    return false;
}

In [5]:
%%R

# My commonly used R imports

require('tidyverse')

R[write to console]: Loading required package: tidyverse

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.2     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ ggplot2   3.4.2     ✔ tibble    3.2.1
✔ lubridate 1.9.2     ✔ tidyr     1.3.0
✔ purrr     1.0.1
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

In [6]:
#To Download PDFs
from urllib.parse import urljoin

In [7]:
#To import camelot and PDF-related items
import camelot
import ghostscript
import sys

In [8]:
%%R

library(jpeg)
library(wordcloud)
library(RColorBrewer)
library(wordcloud2)
library(tm)

R[write to console]: Loading required package: RColorBrewer

R[write to console]: Loading required package: NLP

R[write to console]:
Attaching package: ‘NLP’


R[write to console]: The following object is masked from ‘package:ggplot2’:

    annotate

In [9]:
from sklearn.feature_extraction.text import CountVectorizer

In [10]:
%%R
library(vistime)
library(shiny)
library(plotly)
#for timeline plotting

R[write to console]:
Attaching package: ‘plotly’


R[write to console]: The following object is masked from ‘package:ggplot2’:

    last_plot


R[write to console]: The following object is masked from ‘package:stats’:

    filter


R[write to console]: The following object is masked from ‘package:graphics’:

    layout

In [11]:
from collections import Counter

# Reading the Data

In [12]:
df_secondary_income_data=pd.read_csv("secondary_income_data.csv")
df_pri_plus_sec_merged=pd.read_csv("pri_plus_sec_merged_df.csv")

# Merging the Data

In [13]:
import pandas as pd

# Assuming you have the two datasets: df_secondary_income_data and df_pri_plus_sec_merged

# Merge the datasets on the 'Place_county_or_subcounty' column, retaining only the rows present in df_pri_plus_sec_merged
merged_df = df_secondary_income_data.merge(df_pri_plus_sec_merged, how='inner', left_on='County_slash_Sub_County', right_on='Place_county_or_subcounty')


merged_df

    Unnamed: 0_x County_slash_Sub_County_x lighting_Conventional_Households  \
0              0                   MOMBASA                          376,295
1              7                     KWALE                          172,802
2             13                    KILIFI                          297,990
3             23                TANA RIVER                           66,984
4             27                      LAMU                           34,231
5             30              TAITA/TAVETA                           94,468
6             35                   GARISSA                          138,940
7             43                     WAJIR                          126,878
8             52                   MANDERA                          123,954
9             60                  MARSABIT                           76,689
10            68                    ISIOLO                           53,217
11            72                      MERU                          423,931
12           585             THARAKA-NITHI                          109,450
13           591                      EMBU                          182,427
14           597                     KITUI                          261,814
15           616                  MACHAKOS                          399,523
16           626                   MAKUENI                          243,979
17           636                 NYANDARUA                          178,224
18           644                     NYERI                          244,564
19           669                 KIRINYAGA                          203,576
20           675                  MURANG'A                          317,496
21           684                    KIAMBU                          792,333
22           698                   TURKANA                          162,627
23           706                WEST POKOT                          115,761
24           712                   SAMBURU                           63,951
25           716               TRANS NZOIA                          222,989
26           722               UASIN GISHU                          301,110
27           729           ELGEYO/MARAKWET                           99,119
28           734                     NANDI                          199,040
29           741                   BARINGO                          141,877
30           749                  LAIKIPIA                          145,776
31           755                    NAKURU                          598,237
32           767                     NAROK                          238,115
33           775                   KAJIADO                          313,218
34           782                   KERICHO                          205,932
35           789                     BOMET                          187,230
36           795                  KAKAMEGA                          432,284
37           809                    VIHIGA                          143,288
38           816                   BUNGOMA                          357,714
39           828                     BUSIA                          197,944
40           829                     BUSIA                          197,944
41           836                     SIAYA                          249,341
42           837                     SIAYA                          249,341
43           843                    KISUMU                          296,846
44           851                  HOMA BAY                          260,290
45           860                    MIGORI                          238,133
46           869                     KISII                          307,254
47           881                   NYAMIRA                          150,499
48           887              NAIROBI CITY                        1,494,676

   lighting_Mains_Electricity lighting_Paraffin_Pressure_lamp  \
0                        85.9                             0.5
1                        31.5                             0.5
2                        38.5                             0.6
3                        25.6                             0.2
4                        43.2                             0.2
5                        47.6                             0.3
6                        23.5                             0.2
7                        14.1                             0.1
8                        15.7                             0.2
9                        21.3                             0.2
10                       40.6                             0.3
11                       40.2                             0.5
12                       34.7                             0.4
13                         47                             0.4
14                       17.1                             0.5
15                       48.3                             0.6
16                       20.4                             0.7
17                       41.3                             0.4
18                       71.8                             0.4
19                       65.3                             0.4
20                       60.5                             0.5
21                       91.7                             0.2
22                        8.6                             0.1
23                       11.8                             0.2
24                       14.8                             0.3
25                       37.9                             0.4
26                       63.8                             0.2
27                       24.3                             0.3
28                       30.7                             0.3
29                       28.3                             0.3
30                       42.2                             0.3
31                       64.4                             0.2
32                       19.7                             0.2
33                       67.4                             0.3
34                       44.9                             0.2
35                       22.1                             0.2
36                       25.1                             0.3
37                       38.4                             0.3
38                       21.6                             0.4
39                       26.1                             0.3
40                       26.1                             0.3
41                       19.7                             0.2
42                       19.7                             0.2
43                       52.6                             0.3
44                       18.4                             0.3
45                       23.3                             0.3
46                       39.3                             0.4
47                       42.9                             0.5
48                       96.5                             0.1

   lighting_Paraffin_Lantern lighting_Paraffin_Tin_Lamp lighting_Gas_Lamp  \
0                        2.7                        6.3               0.1
1                          6                       29.5               0.2
2                        6.1                       26.7               0.1
3                        2.4                        7.1               0.5
4                        3.6                        7.2               0.1
5                       10.7                        9.6                 0
6                        0.7                        1.5               2.8
7                        0.6                        0.9               2.8
8                        0.5                          1               2.6
9                        2.7                        2.8               1.6
10                       3.8                        3.7               1.2
11                        11                       13.9               0.2
12                         9                       13.1               0.1
13                         8                       11.8               0.1
14                      13.8                        9.4               0.2
15                      11.6                        7.7               0.1
16                        16                         10               0.1
17                        15                        8.1               0.1
18                       8.1                        8.1               0.1
19                       9.3                       12.5                 0
20                      12.5                       14.3               0.1
21                       2.6                        2.2                 0
22                       0.9                        1.8               0.3
23                       4.7                        5.1               0.2
24                       3.3                        5.5               0.3
25                       9.8                         16               0.1
26                         5                        4.4               0.1
27                       4.5                        3.9               0.1
28                       7.1                       11.9               0.1
29                       6.6                        4.8               0.1
30                       8.4                        9.1               0.1
31                       5.8                        4.4               0.1
32                       4.1                        5.6               0.2
33                       3.9                          5               0.1
34                       5.9                        6.3               0.1
35                       4.9                        3.2               0.1
36                       8.8                       20.5               0.1
37                       8.7                       28.2                 0
38                      11.4                       18.5               0.2
39                       8.7                       18.3               0.1
40                       8.7                       18.3               0.1
41                       6.7                       17.1               0.1
42                       6.7                       17.1               0.1
43                       5.2                       12.5               0.1
44                       6.9                       14.4               0.2
45                         9                       17.3               0.2
46                      13.6                       20.1               0.1
47                      16.1                       19.5               0.1
48                       0.8                        0.8                 0

   lighting_Wood lighting_Solar_and_Solar_Torch_and_Battery_Torch  \
0              0                                      1.5 0.4 0.3
1            1.7                                     22.8 2.7 3.9
2            1.3                                     20.0 2.4 2.9
3            6.8                                   20.9 12.1 21.7
4            1.4                                     28.3 5.8 8.3
5            0.2                                     24.4 2.8 2.8
6           11.9                                   12.7 10.9 32.1
7           15.4                                   11.6 11.2 42.2
8           26.8                                     9.9 8.2 34.1
9           14.2                                   15.1 12.6 28.4
10           6.7                                     9.1 9.0 24.6
11           1.5                                     18.8 3.6 8.3
12           2.1                                    17.1 3.9 18.2
13           0.4                                     21.1 2.8 6.6
14           1.9                                    37.3 6.7 11.7
15           0.2                                     25.6 2.9 0.9
16           0.3                                     44.0 4.2 2.9
17           0.1                                     28.4 2.7 1.1
18           0.1                                      8.4 1.2 0.7
19           0.1                                      8.5 1.2 0.9
20           0.1                                      9.2 1.2 0.5
21             0                                      1.2 0.3 0.2
22          49.1                                    6.2 12.1 18.2
23          31.7                                   15.1 11.8 18.6
24          36.3                                    13.3 9.6 15.7
25           0.7                                     23.9 7.5 1.0
26           0.3                                     14.9 8.5 0.8
27           9.9                                    25.7 23.7 6.2
28           0.3                                    28.6 17.8 1.4
29          18.2                                    21.9 10.1 8.3
30           3.8                                     26.4 5.3 2.3
31           0.4                                     14.5 6.5 1.2
32           5.5                                    37.7 20.1 4.5
33             1                                     15.5 3.6 1.4
34           0.3                                    20.9 17.8 1.5
35           0.8                                    33.5 30.1 2.7
36           0.4                                     36.7 6.2 0.3
37           0.2                                     20.0 3.2 0.3
38           0.9                                     36.4 8.2 0.6
39           0.4                                     37.9 5.9 0.5
40           0.4                                     37.9 5.9 0.5
41           0.2                                     50.8 2.8 0.4
42           0.2                                     50.8 2.8 0.4
43           0.2                                     26.2 1.6 0.2
44           0.6                                     52.5 3.2 0.4
45           0.8                                     41.3 3.6 0.7
46           0.7                                     20.5 3.1 0.4
47           0.9                                     15.5 2.7 0.6
48             0                                      0.2 0.1 0.1

   lighting_Solar lighting_Torch_slash_Spotlight_Solar_Charged  \
0             1.5                                          0.4
1            22.8                                          2.7
2            20.0                                          2.4
3            20.9                                         12.1
4            28.3                                          5.8
5            24.4                                          2.8
6            12.7                                         10.9
7            11.6                                         11.2
8             9.9                                          8.2
9            15.1                                         12.6
10            9.1                                          9.0
11           18.8                                          3.6
12           17.1                                          3.9
13           21.1                                          2.8
14           37.3                                          6.7
15           25.6                                          2.9
16           44.0                                          4.2
17           28.4                                          2.7
18            8.4                                          1.2
19            8.5                                          1.2
20            9.2                                          1.2
21            1.2                                          0.3
22            6.2                                         12.1
23           15.1                                         11.8
24           13.3                                          9.6
25           23.9                                          7.5
26           14.9                                          8.5
27           25.7                                         23.7
28           28.6                                         17.8
29           21.9                                         10.1
30           26.4                                          5.3
31           14.5                                          6.5
32           37.7                                         20.1
33           15.5                                          3.6
34           20.9                                         17.8
35           33.5                                         30.1
36           36.7                                          6.2
37           20.0                                          3.2
38           36.4                                          8.2
39           37.9                                          5.9
40           37.9                                          5.9
41           50.8                                          2.8
42           50.8                                          2.8
43           26.2                                          1.6
44           52.5                                          3.2
45           41.3                                          3.6
46           20.5                                          3.1
47           15.5                                          2.7
48            0.2                                          0.1

   lighting_Torch_slash_Spotlight_Dry_cells lighting_Candle  \
0                                       0.3             2.2
1                                       3.9             0.9
2                                       2.9             1.2
3                                      21.7             2.3
4                                       8.3             1.4
5                                       2.8             1.2
6                                      32.1             1.4
7                                      42.2             0.6
8                                      34.1             0.8
9                                      28.4             0.9
10                                     24.6             0.7
11                                      8.3             1.5
12                                     18.2             1.1
13                                      6.6             1.5
14                                     11.7             0.9
15                                      0.9             1.8
16                                      2.9               1
17                                      1.1             1.6
18                                      0.7               1
19                                      0.9             1.5
20                                      0.5             0.9
21                                      0.2             1.5
22                                     18.2             1.8
23                                     18.6             0.7
24                                     15.7             0.6
25                                      1.0               2
26                                      0.8             1.7
27                                      6.2             1.1
28                                      1.4             1.1
29                                      8.3             1.1
30                                      2.3             1.2
31                                      1.2             1.8
32                                      4.5             1.4
33                                      1.4             1.7
34                                      1.5             1.4
35                                      2.7             0.8
36                                      0.3             0.8
37                                      0.3             0.5
38                                      0.6             1.1
39                                      0.5             1.4
40                                      0.5             1.4
41                                      0.4             1.4
42                                      0.4             1.4
43                                      0.2             1.1
44                                      0.4             1.2
45                                      0.7               2
46                                      0.4             1.2

In [14]:
merged_df.to_csv("df_edu_plus_income_plus_siaya_busia.csv")