# Setting Everything Up

In [1]:
import pandas as pd
from datetime import datetime

In [2]:
#import the file from the web
import requests
from bs4 import BeautifulSoup
import pandas as pd
from unicodedata import normalize
import re
from datetime import datetime
from pandas import read_csv 
from sklearn.feature_extraction.text import CountVectorizer
import json
from flatten_json import flatten


# I can give a number or use None to remove maximum ceiling & display all columns
pd.options.display.max_columns = None

# # I want to be able to see the entire narrative, so remove the maximum width for each column
# pd.options.display.max_colwidth = None

# pd.options.display.float_format = '{:,.0f}'.format

import string

%matplotlib inline

In [3]:
%load_ext rpy2.ipython
%load_ext autoreload
%autoreload 2

%matplotlib inline  
from matplotlib import rcParams
rcParams['figure.figsize'] = (8, 8)

import warnings
from rpy2.rinterface import RRuntimeWarning
warnings.filterwarnings("ignore") # Ignore all warnings
# warnings.filterwarnings("ignore", category=RRuntimeWarning) # Show some warnings

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import display, HTML

In [4]:
%%javascript
// Disable auto-scrolling
IPython.OutputArea.prototype._should_scroll = function(lines) {
    return false;
}

In [5]:
%%R

# My commonly used R imports

require('tidyverse')

R[write to console]: Loading required package: tidyverse

── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──
✔ ggplot2 3.4.0      ✔ purrr   1.0.1
✔ tibble  3.1.8      ✔ dplyr   1.0.10
✔ tidyr   1.3.0      ✔ stringr 1.5.0
✔ readr   2.1.3      ✔ forcats 1.0.0
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()

In [6]:
#To Download PDFs
from urllib.parse import urljoin

In [7]:
#To import camelot and PDF-related items
import camelot
import ghostscript
import sys

In [8]:
%%R

library(jpeg)
library(wordcloud)
library(RColorBrewer)
library(wordcloud2)
library(tm)

R[write to console]: Loading required package: RColorBrewer

R[write to console]: Loading required package: NLP

R[write to console]:
Attaching package: ‘NLP’


R[write to console]: The following object is masked from ‘package:ggplot2’:

    annotate

In [9]:
from sklearn.feature_extraction.text import CountVectorizer

In [10]:
%%R
library(vistime)
library(shiny)
library(plotly)
library(ggrepel)
#for timeline plotting

R[write to console]:
Attaching package: ‘plotly’


R[write to console]: The following object is masked from ‘package:ggplot2’:

    last_plot


R[write to console]: The following object is masked from ‘package:stats’:

    filter


R[write to console]: The following object is masked from ‘package:graphics’:

    layout

In [11]:
from collections import Counter

# How do different variables affect education outcomes in Kenya

# Reading the data

In [73]:
df_kenya_education=pd.read_csv("df_edu_no_total_updated.csv")
df_kenya_education

,Unnamed: 0.2,County,equitable_share_2020_21,equitable_share_2021_22_plus,conditional_grant_2020_21,conditional_grant_2021_22_plus,annual_own_source_revenue_2020_21,annual_own_source_revenue_2021_22_plus,total_revenue_2020_21,total_revenue_2021_22_plus,number_x,county,number_of_schools,total_enrolment,average_school_size,place,population,land_area_km_sq,pop_density_per_km_sq,county_ptr,public_enrolment,public_teachers,public_PTR,private_enrolment,private_teachers,private_PTR,overall_public_plus_private_enrolment,public_over_overall_enrolment_as_pct,overall_pri_ptr_county,overall_pri_ptr_enrolment,overall_pri_ptr_teachers,overall_pri_ptr_PTR,txtbk_no,txtbk_county,txtbk_grade_1,txtbk_grade_2,txtbk_grade_3,pupil_textbook_ratio,s_number_elec,county_elec,national_grid,solar,no_power,elec_table_total,no_power_pct,with_power_pct,with_national_grid_pct,complete_dig_SN,complete_dig_county,number_of_pri_schools_by_2016,number_of_schools_w_complete_digital_devices,pct_installed,detailed_digi_SN,detailed_digi_county,installed_learner_digi_devices,installed_learner_digi_devices.1,Installed_digi_content_server_and_wireless_routers,installed_projectors,installed_special_needs_edu_devices,nasmla_number,nasmla_county,mathematics_mean,mathematics_SE,english_mean,english_SE,kiswahili_mean,kiswahili_SE,county_lower,Unnamed: 0.1,name,capital,code,sub_counties,sub_counties_lower,Place_county_or_subcounty,total_and_gender,number_y,dont_know_number,dont_know_number_percent,not_stated_number,at_school_or_learning_institution_number,at_school_or_learning_institution_pct,after_completion_number,after_completion_pct,before_completion_number,before_completion_pct,never_been_to_school_or_learning_institution_number,never_been_to_school_or_learning_institution_pct,Unnamed: 0,male_Place_county_or_subcounty,male_total_and_gender,male_number,male_dont_know_number,male_dont_know_number_percent,male_not_stated_number,male_at_school_or_learning_institution_number,male_at_school_or_learning_institution_pct,male_after_completion_number,male_after_completion_pct,male_before_completion_number,male_before_completion_pct,male_never_been_to_school_or_learning_institution_number,male_never_been_to_school_or_learning_institution_pct,male_Place_county_or_subcounty_lower,name_lower,county_pupil_tr,pre_primary_pupil_teacher_ratio,secondary_pupil_teacher_ratio,female_Place_county_or_subcounty,female_total_and_gender,female_number,female_dont_know_number,female_dont_know_number_percent,female_not_stated_number,female_at_school_or_learning_institution_number,female_at_school_or_learning_institution_pct,female_after_completion_number,female_after_completion_pct,female_before_completion_number,female_before_completion_pct,female_never_been_to_school_or_learning_institution_number,female_never_been_to_school_or_learning_institution_pct,public_primary_enrolment_as_pct_of_overall_enrolment,never_been_to_school_over_population_pct,before_completion_over_population_pct,left_school_before_plus_after_completion,left_school_over_left_before_and_after_as_pct,after_completion_over_left_before_and_after_as_pct,never_been_to_school_over_left_before_and_after_pct,population_per_no_of_schools_over_area
0,0,Baringo,"5,095.65","6,369.39",752.87,681.62,205.2,258.55,"6,053.72","7,309.56",1,Baringo,841,"161,919",193,Baringo,"666,763","10,976.40",61,Baringo,"143,618","5,595",26,"18,301",883,21.0,"161,919",88.697435,Baringo,"161,919","6,478",25.0,1,Baringo,1.01,1.01,1.39,1.13,30,Baringo,566,183,51,800,6.375000,93.625000,70.750000,1,Baringo,635.0,633.0,99.69,1,Baringo,"19,283","1,266",633,633,29.0,1,Baringo,500.5,56.9,499.3,65.1,493.6,61.7,baringo,459.0,Baringo,Kabarnet,NaN,NaN,NaN,BARINGO,BARINGO,"609,555","6,530",1.1,44,"253,878",41.6,"124,066",20.4,"67,739",11.1,"157,298",25.8,704.0,BARINGO,Male,"306,702","3,456",1.1,18,"130,797",42.6,"64,231",20.9,"32,867",10.7,"75,333",24.6,baringo,baringo,Baringo,29.2,25.7,BARINGO,Female,"302,842","3,074",1,26.0,"123,075",40.6,"59,832",19.8,"34,871",11.5,"81,964",27.1,88.697435,23.591291,10.159382,"191,805",35.316598,64.683402,82.009332,0.07222966008
1,1,Bomet,"5,507.10","6,691.10",832.35,806.48,183.01,300,"6,522.46","7,797.58",2,Bomet,968,"231,197",239,Bomet,"875,689","2,530.90",346,Bomet,"198,857","4,938",40,"32,340","2,792",12.0,"231,197",86.011929,Bomet,"231,197","7,730",30.0,2,Bomet,0.99,0.91,1.00,0.96,36,Bomet,666,1,24,691,3.473227,96.526773,96.382055,2,Bomet,632.0,630.0,99.68,2,Bomet,"27,609","1,260",630,630,NaN,2,Bomet,485.2,27.8,462.2,21.5,447.3,24.2,bomet,485.0,Bomet,Bomet,36.0,NaN,NaN,BOMET,BOMET,"810,122","6,730",0.8,75,"400,330",49.4,"169,658",20.9,"160,702",19.8,"72,627",9.0,848.0,BOMET,Male,"400,694","3,572",0.9,41,"205,930",51.4,"88,746",22.1,"72,327",18.1,"30,078",7.5,bomet,bomet,Bomet,38.8,39.8,BOMET,Female,"409,407","3,158",0.8,34.0,"194,390",47.5,"80,911",19.8,"88,369",21.6,"42,545",10.4,86.011929,8.293698,18.351492,"330,360",48.644509,51.355491,21.984199,0.3574370369
2,2,Bungoma,"8,893.65","10,659.44",876.59,696.07,395.12,500,"10,165.36","11,855.51",3,Bungoma,"1,115","500,157",449,Bungoma,"1,670,570","3,023.90",552,Bungoma,"449,148","8,996",50,"51,009","2,277",22.0,"500,157",89.801402,Bungoma,"500,157","11,273",44.0,3,Bungoma,0.89,0.89,0.90,0.89,39,Bungoma,749,15,23,787,2.922490,97.077510,95.171537,3,Bungoma,741.0,741.0,100.00,3,Bungoma,"58,871","1,482",741,741,24.0,3,Bungoma,433.9,10.3,434.2,12.6,462.6,15.6,bungoma,492.0,Bungoma,Bungoma,39.0,NaN,NaN,BUNGOMA,BUNGOMA,"1,538,767","15,673",1.0,139,"782,677",50.9,"264,282",17.2,"324,058",21.1,"151,938",9.9,929.0,BUNGOMA,Male,"745,883","8,198",1.1,74,"396,144",53.1,"133,462",17.9,"140,682",18.9,"67,323",9.0,bungoma,bungoma,Bungoma,42.0,37.7,BUNGOMA,Female,"792,851","7,473",0.9,65.0,"386,512",48.7,"130,817",16.5,"183,372",23.1,"84,612",10.7,89.801402,9.094980,19.398050,"588,340",55.080056,44.919944,25.824863,0.4954757295
3,3,Busia,"6,013.50","7,172.16",845.88,600.43,322.56,499.8,"7,181.93","8,272.39",4,Busia,568,"250,860",442,Busia,"893,681","1,696.30",527,Busia,"231,765","4,949",47,"19,095",962,20.0,"250,860",92.388185,Busia,"250,860","5,911",42.0,4,Busia,0.82,0.89,0.84,0.85,40,Busia,440,4,1,445,0.224719,99.775281,98.876404,4,Busia,432.0,431.0,99.77,4,Busia,"31,567",864,432,432,17.0,4,Busia,465.9,15.6,475.3,22.7,493.1,22.8,busia,502.0,Busia,Busia,40.0,NaN,NaN,BUSIA,BUSIA,"820,788","5,512",0.7,74,"405,072",49.4,"136,790",16.7,"170,347",20.8,"102,993",12.5,968.0,BUSIA,Male,"388,748","2,991",0.8,35,"202,993",52.2,"70,030",18.0,"73,630",18.9,"39,069",10.0,busia,busia,Busia,46.8,35.5,BUSIA,Female,"432,013","2,521",0.6,39.0,"202,061",46.8,"66,760",15.5,"96,713",22.4,"63,919",14.8,92.388185,11.524582,19.061276,"307,137",55.462872,44.537128,33.533244,0.9275376067
4,7,Elgeyo Marakwet,"3,861.30","4,606.53",735.21,855.35,69.08,166.1,"4,665.58","5,627.98",5,Elgeyo Marakwet,467,"123,818",265,Elgeyo/Marakwet,"454,480","3,032.00",150,Elgeyo Marakwet,"109,641","3,820",29,"14,177",784,18.0,"123,818",88.550130,Elgeyo Marakwet,"123,818","4,604",27.0,5,Elgeyo/Marakwet,0.99,1.00,1.00,1.00,28,Elgeyo/Marakwet,371,19,9,399,2.255639,97.744361,92.982456,5,Elgeyo/Marakwet,369.0,369.0,100.00,5,Elgeyo/Marakwet,"13,964",738,369,369,NaN,5,Elgeyo Marakwet,488.2,14.9,461.0,17.1,495.0,11.9,elgeyo marakwet,452.0,Elgeyo-Marakwet,Iten,28.0,NaN,NaN,ELGEYO/MARAKWET,ELGEYO/MARAKWET,"418,765","3,541",0.8,62,"203,979",48.7,"93,397",22.3,"65,739",15.7,"52,047",12.4,668.0,ELGEYO/MARAKWET,Male,"209,151","1,789",0.9,30,"103,310",49.4,"48,510",23.2,"31,890",15.2,"23,622",11.3,elgeyo/marakwet,elgeyo/marakwet,Elgeyo Marakwet,24.7,27.4,ELGEYO/MARAKWET,Female,"209,602","1,751",0.8,32.0,"100,663",48.0,"44,886",21.4,"33,847",16.1,"28,423",13.6,88.550130,11.451989,14.464663,"159,136",41.309949,58.690051,32.705987,0.3209731458
5,8,Embu,"4,304.40","5,125.24",998.06,607.12,375.33,900,"5,677.78","6,632.36",6,Embu,519,"124,774",240,Embu,"608,599","2,820.70",216,Embu,"101,425","3,694",27,"23,349","1,120",21.0,"124,774",81.286967,Embu,"124,774","4,814",26.0,6,Embu,0.50,0.50,0.50,0.50,14,Embu,370,11,0,381,0.000000,100.000000,97.112861,6,Embu,381.0,381.0,100.00,6,Embu,"12,740",762,381,381,13.0,6,Embu,473.9,14.5,474.3,16.6,461.8,15.2,embu,394.0,Embu,Embu,14.0,NaN,NaN,EMBU,EMBU,"568,228","2,404",0.4,51,"205,389",36.1,"180,500",31.8,"131,329",23.1,"48,555",8.5,284.0,EMBU,Male,"283,024","1,530",0.5,22,"104,132",36.8,"90,744",32.1,"67,774",23.9,"18,822",6.7,embu,embu,Embu,35.8,25.2,EMBU,Female,"285,182",874,0.3,29.0,"101,251",35.5,"89,746",31.5,"63,552",22.3,"29,730",10.4,81.286967,7.978160,21.578905,"311,829",42.115711,57.884289,15.571034,0.4157258003
6,9,Garissa,"7,026.30","7,927.21","1,651.83","1,241.03",103.53,150,"8,781.65","9,318.24",7,Garissa,304,"77,465",255,Garissa,"841,353","44,736.00",19,Garissa,"51,895",926,56,"25,570",785,33.0,"77,465",66.991545,Garissa,"77,465","1,711",45.0,7,Garissa,0.98,1.01,1.01,1.00,7,Garissa,69,176,3,248,1.209677,98.790323,27.822581,7,Garissa,163.0,153.0,93.87,7,Garissa,"7,762",306,153,153,16.0,7,Garissa,398.2,67.2,363.2,67.6,351.8,55.6,garissa,36.0,Garissa,Garissa,7.0,Garissa,garissa,GARISSA,GARISSA,"778,006","27,479",3.5,155,"132,990",17.1,"23,144",3.0,"9,508",1.2,"584,730",75.2,110.0,GARISSA,Male,"425,411","15,564",3.7,93,"77,489",18.2,"15,400",3.6,"5,309",1.2,"311,556",73.2,garissa,garissa,Garissa,44.8,25.4,GARISSA,Female,"352,563","11,913",3.4,62.0,"55,497",15.7,"7,744",2.2,"4,198",1.2,"273,149",77.5,66.991545,69.498772,1.130085,"32,652",29.119196,70.880804,1790.793826,0.0618653557
7,13,Homa Bay,"6,741.45","7,805.35",704.95,607.76,120.41,143.81,"7,566.81","8,556.93",8,Homa Bay,"1,042","313,666",301,Homa Bay,"1,131,950","3,152.50",359,Homa Bay,"279,599","7,226",39,"34,067","1,351",25.0,"313,666",89.139084,Homa Bay,"313,666","8,577",37.0,8,Homa Bay,1.00,1.00,1.00,1.00,43,Homa Bay,763,22,0,785,0.000000,100.000000,97.197452,8,Homa Bay,875.0,875.0,100.00,8,Homa Bay,"34,758","1,752",875,875,NaN,8,Homa Bay,495.0,23.3,515.3,14.9,473.2,6.1,homa bay,513.0,Homa Bay,Homa Bay,43.0,NaN,NaN,HOMA BAY,HOMA BAY,"1,037,468","6,627",0.6,81,"539,753",52.0,"196,288",18.9,"200,313",19.3,"94,406",9.1,1037.0,HOMA BAY,Male,"491,680","3,451",0.7,40,"274,952",55.9,"98,363",20.0,"79,996",16.3,"34,878",7.1,homa bay,homa bay,Homa Bay,60.5,34.4,HOMA BAY,Female,"545,768","3,174",0.6,41.0,"264,796",48.5,"97,920",17.9,"120,311",22.0,"59,526",10.9,89.139084,8.340121,17.696276,"396,601",50.507437,49.492563,23.803773,0.3445913961
8,14,Isiolo,"4,241.10","4,710.39",942.48,813.49,57.18,113.69,"5,240.76","5,637.57",9,Isiolo,163,"35,221",216,Isiolo,"268,002","25,350.60",11,Isiolo,"28,784","1,002",29,"6,437",290,22.0,"35,221",81.723971,Isiolo,"35,221","1,292",27.0,9,Isiolo,1.01,0.98,0.97,0.99,11,Isiolo,41,69,0,110,0.000000,100.000000,37.272727,9,Isiolo,116.0,95.0,81.90,9,Isiolo,"4,048",190,95,95,4.0,9,Isiolo,525.9,24.1,537.4,30.6,547.0,24.6,isiolo,51.0,Isiolo,Isiolo,11.0,Isiolo,isiolo,ISIOLO,ISIOLO,"245,462","1,483",0.6,37,"79,881",32.5,"34,817",14.2,"14,485",5.9,"114,759",46.8,209.0,ISIOLO,Male,"128,141",886,0.7,21,"40,960",32.0,"19,823",15.5,"7,599",5.9,"58,852",45.9,isiolo,isiolo,Isiolo,56.3,19.5,ISIOLO,Female,"117,317",597,0.5,16.0,"38,920",33.2,"14,994",12.8,"6,886",5.9,"55,904",47.7,81.723971,42.820203,5.404810,"49,302",29.380147,70.619853,232.767433,0.06485779623
9,18,Kajiado,"6,424.95","7,954.77",927.74,729.5,862.29,"1,605.36","8,214.97","10,289.63",10,Kajiado,792,"191,184",241,Kajiado,"1,117,840","21,871.10",51,Kajiado,"138,817","3,611",38,"52,367","2,821",19.0,"191,184",72.609110,Kajiado,"191,184","6,432",30.0,10,Kajiado,0.98,0.99,0.99,0.99,34,Kajiado,257,249,16,522,3.065134,96.934866,49.233716,10,Kajiado,395.0,394.0,99.75,10,Kajiado,"15,956",788,394,394,NaN,10,Kajiado,489.9,3.7,465.5,10.9,519.4,19.0,kajiado,474.0,Kajiado,Kajiado,34.0,NaN,NaN,KAJIADO,KAJIADO,"1,016,058","13,146",1.3,327,"389,090",38.3,"319,689",31.5,"111,477",11.0,"182,329",17.9,806.0,KAJIADO,Male,"504,023","7,321",1.5,139,"195,925",38.9,"164,069",32.6,"54,115",10.7,"82,454",16.4,kajiado,kajiado,Kajiado,44.4,25.8,KAJIADO,Female,"512,004","5,824",1.1,188.0,"193,153",37.7,"155,610",30.4,"57,359",11.2,"99,870",19.5,72.609110,16.310832,9.972536,"431,166",25.854775,74.145225,42.287425,0.06453329469
10,19,Kakamega,"10,412.85","12,389.41","1,499.98",844.39,"1,118.24","2,113.00","13,031.06","15,346.80",11,Kakamega,"1,120","555,021",496,Kakamega,"1,867,579","3,020.00",618,Kakamega,"519,857","10,664",49,"35,164","1,825",19.0,"555,021",93.664384,Kakamega,"555,021","12,489",44.0,11,Kakamega,0.97,0.98,0.99,0.98,37,Kakamega,887,9,13,909,1.430143,98.569857,97.579758,11,Kakamega,880.0,879.0,99.89,11,Kakamega,"66,404","1,760",880,880,93.0,11,Kakamega,469.0,18.1,485.1,20.9,503.0,13.8,kakamega,486.0,Kakamega,Kakamega,37.0,NaN,NaN,KAKAMEGA,KAKAMEGA,"1,732,145","11,722",0.7,382,"853,031",49.2,"334,397",19.3,"352,269",20.3,"180,344",10.4,866.0,KAKAMEGA,Male,"828,945","6,139",0.7,170,"428,344",51.7,"162,596",19.6,"157,153",19.0,"74,543",9.0,kakamega,kakamega,Kakamega,63.2,35.0,KAKAMEGA,Female,"903,166","5,583",0.6,212.0,"424,667",47.0,"171,796",19.0,"195,111",21.6,"105,797",11.7,93.664384,9.656566,18.862335,"686,666",51.301360,48.698640,26.263715,0.5521461093
11,20,Kericho,"5,380.50","6,430.66",780.03,722.35,595.98,494.05,"6,756.51","7,647.07",12,Kericho,827,"222,619",269,Kericho,"901,777","2,436.10",370,Kericho,"178,579","5,494",33,"44,040","2,154",20.0,"222,619",80.217322,Kericho,"222,619","7,648",29.0,12,Kericho,0.96,0.97,0.97,0.97,35,Kericho,497,1,0,498,0.000000,100.000000,99.799197,12,Kericho,503.0,502.0,99.80,12,Kericho,"23,783","1,004",502,502,66.0,12,Kericho,457.1,16.4,449.4,20.1,449.5,14.5,kericho,481.0,Kericho,Kericho,35.0,NaN,NaN,KERICHO,KERICHO,"834,061","4,236",0.5,219,"387,109",46.4,"201,479",24.2,"172,473",20.7,"68,545",8.2,827.0,KERICHO,Male,"415,734","2,323",0.6,110,"197,586",47.5,"105,284",25.3,"80,978",19.5,"29,453",7.1,kericho,kericho,Kericho,31.8,33.7,KERICHO,Female,"418,300","1,913",0.5,109.0,"189,513",45.3,"96,187",23.0,"91,489",21.9,"39,089",9.3,80.217322,7.601103,19.125904,"373,952",46.121695,53.878305,18.329893,0.4476087143
12,21,Kiambu,"9,431.70","11,717.53","1,418.16",742.54,"2,425.25","3,883.30","13,275.10","16,343.37",13,Kiambu,899,"347,510",387,Kiambu,"2,417,735","2,538.60",952,Kiambu,"227,580","6,129",37,"119,930","4,227",28.0,"347,510",65.488763,Kiambu,"347,510","10,356",34.0,13,Kiambu,0.94,0.98,0.96,0.96,22,Kiambu,461,0,1,462,0.216450,99.783550,99.783550,13,Kiambu,481.0,481.0,100.00,13,Kiambu,"23,732",962,481,481,50.0,13,Kiambu,554.4,39.2,594.7,26.0,562.0,20.0,kiambu,87.0,Kiambu,Kiambu,22.0,Kiambu,kiambu,KIAMBU,KIAMBU,"2,231,514","13,057",0.6,522,"778,586",34.9,"1,013,910",45.4,"326,845",14.6,"98,594",4.4,533.0,KIAMBU,Male,"1,092,380","7,274",0.7,262,"388,770",35.6,"504,910",46.2,"151,002",13.8,"40,162",3.7,kiambu,kiambu,Kiambu,26.6,25.9,KIAMBU,Female,"1,139,012","5,783",0.5,260.0,"389,788",34.2,"508,948",44.7,"175,810",15.4,"58,423",5.1,65.488763,4.077949,13.518645,"1,340,755",24.377683,75.622317,7.353618,1.059387221
13,25,Kilifi,"10,444.50","11,641.59","1,807.24","2,307.31",833.85,925,"13,085.59","14,873.90",14,Kilifi,842,"353,254",420,Kilifi,"1,453,787","12,539.70",116,Kilifi,"310,881","5,869",53,"42,373","2,063",21.0,"353,254",88.004948,Kilifi,"353,254","7,932",45.0,14,Kilifi,0.93,0.94,0.96,0.94,3,Kilifi,439,101,10,550,1.818182,98.181818,79.818182,14,Kilifi,507.0,507.0,100.00,14,Kilifi,"33,245","1,014",507,507,NaN,14,Kilifi,559.7,12.8,533.4,22.6,581.5,9.5,kilifi,327.0,Kilifi,Kilifi,3.0,NaN,NaN,KILIFI,KILIFI,"1,323,664","9,634",0.7,237,"605,776",45.8,"282,538",21.3,"175,199",13.2,"250,280",18.9,44.0,KILIFI,Male,"636,891","5,214",0.8,110,"308,926",48.5,"154,263",24.2,"86,075",13.5,"82,303",12.9,kilifi,kilifi,Kilifi,20.9,42.7,KILIFI,Female,"686,754","4,420",0.6,126.0,"296,841",43.2,"128,273",18.7,"89,122",13.0,"167,972",24.5,88.004948,17.215727,12.051215,"457,737",38.275036,61.724964,54.677686,0.1376897283
14,26,Kirinyaga,"4,241.10","5,196.18",592.59,726.94,346.52,485,"5,180.21","6,408.11",15,Kirinyaga,355,"108,014",304,Kirinyaga,"610,411","1,478.30",413,Kirinyaga,"76,840","2,535",30,"31,174","1,824",17.0,"108,014",71.138926,Kirinyaga,"108,014","4,359",25.0,15,Kirinyaga,0.91,0.91,0.92,0.91,20,Kirinyaga,197,1,0,198,0.000000,100.000000,99.494949,15,Kirinyaga,199.0,199.0,100.00,15,Kirinyaga,"9,329",398,199,199,15.0,15,Kirinyaga,493.6,15.3,508.6,11.6,496.4,4.3,kirinyaga,435.0,Kirinyaga,Kerugoya/Kutus,20.0,NaN,NaN,KIRINYAGA,KIRINYAGA,"571,312","3,931",0.7,37,"193,518",33.9,"199,413",34.9,"136,968",24.0,"37,445",6.6,482.0,KIRINYAGA,Male,"281,556","2,256",0.8,21,"98,661",35.0,"100,582",35.7,"67,459",24.0,"12,577",4.5,kirinyaga,kirinyaga,Kirinyaga,29.3,26.7,KIRINYAGA,Female,"289,729","1,675",0.6,16.0,"94,852",32.7,"98,822",34.1,"69,497",24.0,"24,867",8.6,71.138926,6.134391,22.438652,"336,381",40.718114,59.281886,11.131723,1.163138474
15,27,Kisii,"7,785.90","8,894.27","1,244.00",728.94,403,700,"9,432.90","10,323.22",16,Kisii,"1,107","309,794",280,Kisii,"1,266,860","1,323.00",958,Kisii,"255,616","7,344",35,"54,178","2,345",23.0,"309,794",82.511604,Kisii,"309,794","9,689",32.0,16,Kisii,1.01,1.01,1.03,1.01,45,Kisii,694,1,3,698,0.429799,99.570201,99.426934,16,Kisii,697.0,696.0,99.86,16,Kisii,"35,050","1,392",696,696,37.0,16,Kisii,478.8,18.7,455.0,16.4,473.0,22.4,kisii,521.0,Kisii,Kisii,45.0,NaN,NaN,KISII,KISII,"1,179,067","6,092",0.5,143,"557,477",47.3,"250,730",21.3,"248,244",21.1,"116,381",9.9,1091.0,KISII,Male,"561,241","3,097",0.6,66,"282,802",50.4,"127,184",22.7,"104,190",18.6,"43,902",7.8,kisii,kisii,Kisii,37.9,29.2,KISII,Female,"617,793","2,995",0.5,77.0,"274,662",44.5,"123,540",20.0,"144,048",23.3,"72,471",11.7,82.511604,9.186572,19.595220,"498,974",49.750889,50.249111,23.324061,0.865010061
16,28,Kisumu,"6,836.40","8,026.14","1,197.23",922.93,822.3,"1,984.00","8,855.93","10,933.07",17,Kisumu,821,"287,164",350,Kisumu,"1,155,574","2,085.40",554,Kisumu,"254,011","6,174",41,"33,153","1,554",21.0,"287,164",88.455029,Kisumu,"287,164","7,728",37.0,17,Kisumu,0.91,0.92,0.93,0.92,42,Kisumu,615,0,0,615,0.000000,100.000000,100.000000,17,Kisumu,613.0,613.0,100.00,17,Kisumu,"30,716","1,226",613,613,110.0,17,Kisumu,464.8,24.0,484.0,27.4,459.6,28.6,kisumu,NaN,Kisumu,Kisumu,42.0,NaN,NaN,KISUMU,KISUMU,NaN,"7,121",0.7,301,"504,812",47.6,"284,283",26.8,"188,709",17.8,75998,7.2,NaN,KISUMU,Male,"511,739","3,831",0.7,148,"253,600",49.6,"144,815",28.3,"80,326",15.7,"29,019",5.7,kisumu,kisumu,Kisumu,29.0,31.1,KISUMU,Female,"549,465",45.7,"139,457",25.4,"108,379",19.7,"46,977",8.5,NaN,NaN,NaN,NaN,88.455029,6.576645,16.330326,"472,992",39.896869,60.103131,16.067502,0.6749401062
17,29,Kitui,"8,830.35","10,393.97",833.88,658.52,326.45,850,"9,990.68","11,902.49",18,Kitui,"1,620","335,078",207,Kitui,"1,136,187","30,429.50",37,Kitui,"318,630","10,142",31,"16,448","1,126",15.0,"335,078",95.091292,Kitui,"335,078","11,268",30.0,18,Kitui,0.98,0.98,0.98,0.98,15,Kitui,885,484,45,"1,414",3.182461,96.817539,62.588402,18,Kitui,NaN,NaN,99.60,18,Kitui,"42,732","2,466","1,233","1,233",NaN,18,Kitui,482.6,17.6,448.9,15.1,467.7,12.7,kitui,398.0,Kitui,Kitui,15.0,NaN,NaN,KITUI,KITUI,"1,056,907","11,795",1.1,149,"490,726",46.4,"265,238",25.1,"152,030",14.4,"136,969",13.0,305.0,KITUI,Male,"508,247","6,431",1.3,61,"250,178",49.2,"127,266",25.0,"72,606",14.3,"51,705",10.2,kitui,kitui,Kitui,21.0,28.9,KITUI,Female,"548,634","5,364",1,88.0,"240,536",43.8,"137,968",25.1,"79,419",14.5,"85,259",15.5,95.091292,12.055146,13.380720,"417,268",36.434618,63.565382,32.825187,0.02304835768

# Reading the data in R

In [74]:
%%R 

# df_kenya_education_r_incorrect_female <- read_csv('df_x_y_cleaned_with_teacher_ratio.csv', show_col_types = FALSE)
df_kenya_education_no_total_r <- read_csv('df_edu_no_total_updated.csv', show_col_types = FALSE)

New names:
• `` -> `...1`

# Background guide for regression analysis

# So far, I am investigating the following y variables:

1) Never been to school
2) Left school before completion
3) NASMLA scores

# So far, I am looking at working the following x variables to create a model to predict the y variables mentioned:
I need to change that: maybe there is a way to do that altogether. Some possible x variables could be:
1) Number of schools per area (how do I normalise by population?)
2) Average school size
3) Pupil Teacher ratio
4) Pupil textbook ratio
5) Electricity
6) Digital Devices
7) County Government revenues
8) Private/ public dichotomy

# For Linear regressions
1) I think I need to go variable by variable. Currently using never been to school as the y variable because that is the measure of access to education I am using. 
2) Given findings on dropout rate, I think it would be an interesting thing to investigate, but not sure whether a sign of outliers would make for a good model?

In [75]:
# model <- lm(Y ~ X, data)
# create a linear regression


# summary(model)
# get a summary (slope, intercept, R2, p-values)


# predict(model) 
# the Y values your model predicts (points on the red line)


# residuals(model)
# Errors...ie, distances from the regression line to each dot)


# rstandard(model)
# Errors, but expressed as a z-score (error expressed as a number of standard deviations from the mean error)

In [76]:
# %%R 
# # guide for linear regression
# model <- lm(Y ~ X, data)
# summary(model)

# County Government Revenues (X1)

#### Dropout rates

In [77]:
%%R 
# guide for linear regression
model <- lm(left_school_over_left_before_and_after_as_pct ~ total_revenue_2021_22_plus, df_kenya_education_no_total_r)
summary(model)

Call:
lm(formula = left_school_over_left_before_and_after_as_pct ~
    total_revenue_2021_22_plus, data = df_kenya_education_no_total_r)

Residuals:
     Min       1Q   Median       3Q      Max
-14.0975  -7.8926  -0.6719   7.0521  18.7073

Coefficients:
                             Estimate Std. Error t value Pr(>|t|)
(Intercept)                46.5198369  3.0308114  15.349   <2e-16 ***
total_revenue_2021_22_plus -0.0006439  0.0002696  -2.389   0.0212 *
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 9.748 on 45 degrees of freedom
Multiple R-squared:  0.1125,	Adjusted R-squared:  0.09279
F-statistic: 5.705 on 1 and 45 DF,  p-value: 0.02117

# What do we learn from above regression?

This runs dropout rate (Y) against revenue (x). <br />
The p-value is low. Therefore, we can conclude that the explanatory variable affects the dependent variable. That is, the revenues affect the dropout rates<br />
The multiple r squared value is 11%, meaning that only 11% of the dropout rate is explained by the revenue of a county

#### Access to education rates

In [78]:
%%R 
# guide for linear regression
model <- lm(never_been_to_school_or_learning_institution_pct ~ total_revenue_2021_22_plus, df_kenya_education_no_total_r)
summary(model)

Call:
lm(formula = never_been_to_school_or_learning_institution_pct ~
    total_revenue_2021_22_plus, data = df_kenya_education_no_total_r)

Residuals:
    Min      1Q  Median      3Q     Max
-15.348 -12.066  -9.659   2.256  57.414

Coefficients:
                             Estimate Std. Error t value Pr(>|t|)
(Intercept)                22.3374121  6.3967166   3.492  0.00109 **
total_revenue_2021_22_plus -0.0002344  0.0005690  -0.412  0.68238
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 20.57 on 45 degrees of freedom
Multiple R-squared:  0.003756,	Adjusted R-squared:  -0.01838
F-statistic: 0.1696 on 1 and 45 DF,  p-value: 0.6824

# What do we learn from above regression?

This runs access to education (Y) against revenue (x). <br />
The p-value is high. Therefore, the x variable does not affect the dependent variable in a statistically significant way. That is, the revenues do not affect access to education in a statistically significant way<br />

#### NASMLA Math Scores

In [107]:
%%R 
# guide for linear regression
model <- lm(mathematics_mean ~ total_revenue_2021_22_plus, df_kenya_education_no_total_r)
summary(model)

Call:
lm(formula = mathematics_mean ~ total_revenue_2021_22_plus, data = df_kenya_education_no_total_r)

Residuals:
    Min      1Q  Median      3Q     Max
-99.888 -26.675  -2.308  27.610 131.919

Coefficients:
                            Estimate Std. Error t value Pr(>|t|)
(Intercept)                4.693e+02  1.351e+01  34.748   <2e-16 ***
total_revenue_2021_22_plus 3.085e-03  1.201e-03   2.567   0.0136 *
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 43.44 on 45 degrees of freedom
Multiple R-squared:  0.1278,	Adjusted R-squared:  0.1084
F-statistic: 6.592 on 1 and 45 DF,  p-value: 0.01364

# What do we learn from above regression?

This runs dropout rate (Y) against revenue (x). <br />
The p-value is low. Therefore, we can conclude that the explanatory variable affects the dependent variable. That is, the revenues affect the mathematics scores in a statistically signifcant way<br />
The multiple r squared value is 12%, meaning that only 12% of the variance in math scores can be explained by the revenue of a county

# Average School Size (X2)
From plotting, unlikely to have impact because school size might be too flimsy a variable. For instance, the school could be big but have a lot of teachers and a lot of revenue etc or the school could be small and in that smallness have no teachers or revenue etc. But always still worth exploring

#### Dropout rates

In [79]:
%%R 
# guide for linear regression
model <- lm(left_school_over_left_before_and_after_as_pct ~ average_school_size, df_kenya_education_no_total_r)
summary(model)

Call:
lm(formula = left_school_over_left_before_and_after_as_pct ~
    average_school_size, data = df_kenya_education_no_total_r)

Residuals:
     Min       1Q   Median       3Q      Max
-21.9975  -8.2090   0.5241   7.4610  21.1904

Coefficients:
                    Estimate Std. Error t value Pr(>|t|)
(Intercept)         28.88798    6.20813   4.653 2.89e-05 ***
average_school_size  0.03719    0.01997   1.862   0.0691 .
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 9.97 on 45 degrees of freedom
Multiple R-squared:  0.07154,	Adjusted R-squared:  0.05091
F-statistic: 3.468 on 1 and 45 DF,  p-value: 0.06912

# What do we learn from above regression?

This runs dropout rate (Y) against average school size (x). <br />
The p-value is high. Therefore, we can conclude that the explanatory variable does not affect the dependent variable in a statistically significant way. That is, the average school size does not affect the dropout rates in a statistically significant way<br />
Question: Once p-value is high, is it worth analysing the multiple r-squared? The multiple r squared value is 7%, meaning that only 7% of the variance in dropout rate is explained by the revenue of a county

#### Access to education rates

In [80]:
%%R 
# guide for linear regression
model <- lm(never_been_to_school_or_learning_institution_pct ~ average_school_size, df_kenya_education_no_total_r)
summary(model)

Call:
lm(formula = never_been_to_school_or_learning_institution_pct ~
    average_school_size, data = df_kenya_education_no_total_r)

Residuals:
    Min      1Q  Median      3Q     Max
-18.303 -12.982  -8.769   2.531  54.955

Coefficients:
                    Estimate Std. Error t value Pr(>|t|)
(Intercept)         33.46571   12.66750   2.642   0.0113 *
average_school_size -0.04452    0.04075  -1.093   0.2804
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 20.34 on 45 degrees of freedom
Multiple R-squared:  0.02584,	Adjusted R-squared:  0.004194
F-statistic: 1.194 on 1 and 45 DF,  p-value: 0.2804

# What do we learn from above regression?

This runs access to education rate (Y) against average school size (x). <br />
The p-value is high. Therefore, we can conclude that the explanatory variable does not affect the dependent variable in a statistically significant way. That is, the average school size does not affect the dropout rates in a statistically significant way<br />
Question: Once p-value is high, is it worth analysing the multiple r-squared? The multiple r squared value is 2%, meaning that only 2% of the variance in access to education is explained by the revenue of a county

#### NASMLA Math Scores

In [108]:
%%R 
# guide for linear regression
model <- lm(mathematics_mean ~ average_school_size, df_kenya_education_no_total_r)
summary(model)

Call:
lm(formula = mathematics_mean ~ average_school_size, data = df_kenya_education_no_total_r)

Residuals:
     Min       1Q   Median       3Q      Max
-102.927  -26.523   -9.942   23.064  133.815

Coefficients:
                     Estimate Std. Error t value Pr(>|t|)
(Intercept)         507.37913   28.94105  17.531   <2e-16 ***
average_school_size  -0.02452    0.09311  -0.263    0.794
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 46.48 on 45 degrees of freedom
Multiple R-squared:  0.001539,	Adjusted R-squared:  -0.02065
F-statistic: 0.06934 on 1 and 45 DF,  p-value: 0.7935

# What do we learn from above regression?

This runs NASMLA mathematics scores (Y) against average school size (x). <br />
The p-value is high. Therefore, we can conclude that the explanatory variable does not affect the dependent variable in a statistically significant way. That is, the average school size does not affect the math scores in a statistically significant way<br />

# Pupil Teacher Ratio (X3)

#### Dropout rates

In [81]:
%%R 
# guide for linear regression
model <- lm(left_school_over_left_before_and_after_as_pct ~ overall_pri_ptr_PTR, df_kenya_education_no_total_r)
summary(model)

Call:
lm(formula = left_school_over_left_before_and_after_as_pct ~
    overall_pri_ptr_PTR, data = df_kenya_education_no_total_r)

Residuals:
     Min       1Q   Median       3Q      Max
-20.4063  -8.0336  -0.1463   7.9727  17.2160

Coefficients:
                    Estimate Std. Error t value Pr(>|t|)
(Intercept)          33.6839     5.5259   6.096 2.44e-07 ***
overall_pri_ptr_PTR   0.1980     0.1539   1.287    0.205
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 9.859 on 44 degrees of freedom
  (1 observation deleted due to missingness)
Multiple R-squared:  0.03629,	Adjusted R-squared:  0.01438
F-statistic: 1.657 on 1 and 44 DF,  p-value: 0.2048

# What do we learn from above regression?

This runs dropout rate (Y) against the overall primary school pupil teacher ratio (x). <br />
The p-value is high. Therefore, we can conclude that the explanatory variable does not affect the dependent variable in a statistically significant way. That is, the overall primary school pupil teacher ratio does not affect the dropout rates in a statistically significant way<br />

#### Access to education rates

In [82]:
%%R 
# guide for linear regression
model <- lm(never_been_to_school_or_learning_institution_pct ~ overall_pri_ptr_PTR, df_kenya_education_no_total_r)
summary(model)

Call:
lm(formula = never_been_to_school_or_learning_institution_pct ~
    overall_pri_ptr_PTR, data = df_kenya_education_no_total_r)

Residuals:
    Min      1Q  Median      3Q     Max
-22.778 -10.748  -3.127   3.530  44.522

Coefficients:
                    Estimate Std. Error t value Pr(>|t|)
(Intercept)         -25.3788     9.1516  -2.773  0.00811 **
overall_pri_ptr_PTR   1.3195     0.2548   5.178 5.34e-06 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 16.33 on 44 degrees of freedom
  (1 observation deleted due to missingness)
Multiple R-squared:  0.3787,	Adjusted R-squared:  0.3646
F-statistic: 26.82 on 1 and 44 DF,  p-value: 5.336e-06

# What do we learn from above regression?

This runs access to education rate (Y) against overall primary school pupil teacher ratio (x). <br />
The p-value is low. Therefore, we can conclude that the explanatory variable affects the dependent variable in a statistically significant way. That is, the overall primary school pupil teacher ratio affects the access to education rates in a statistically significant way<br />
The multiple r squared value is 37%, meaning that 37% of the variance in access to education is explained by the overall primary school pupil teacher ratio of a county

#### NASMLA Math Scores

In [109]:
%%R 
# guide for linear regression
model <- lm(mathematics_mean ~ overall_pri_ptr_PTR, df_kenya_education_no_total_r)
summary(model)

Call:
lm(formula = mathematics_mean ~ overall_pri_ptr_PTR, data = df_kenya_education_no_total_r)

Residuals:
    Min      1Q  Median      3Q     Max
-82.996 -21.911  -6.994  22.227 101.065

Coefficients:
                    Estimate Std. Error t value Pr(>|t|)
(Intercept)         550.3596    22.3328  24.644   <2e-16 ***
overall_pri_ptr_PTR  -1.5370     0.6218  -2.472   0.0174 *
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 39.84 on 44 degrees of freedom
  (1 observation deleted due to missingness)
Multiple R-squared:  0.1219,	Adjusted R-squared:  0.102
F-statistic:  6.11 on 1 and 44 DF,  p-value: 0.01738

# What do we learn from above regression?

This runs NASMLA math scores (Y) against overall primary school pupil teacher ratio (x). <br />
The p-value is low. Therefore, we can conclude that the explanatory variable affects the dependent variable in a statistically significant way. That is, the overall primary school pupil teacher ratio affects the math scores in a statistically significant way<br />
The multiple r squared value is 12%, meaning that 12% of the variance in access to education is explained by the overall primary school pupil teacher ratio of a county

# Pupil Textbook Ratio (X4)

#### Dropout rates

In [83]:
%%R 
# guide for linear regression
model <- lm(left_school_over_left_before_and_after_as_pct ~ pupil_textbook_ratio, df_kenya_education_no_total_r)
summary(model)

Call:
lm(formula = left_school_over_left_before_and_after_as_pct ~
    pupil_textbook_ratio, data = df_kenya_education_no_total_r)

Residuals:
     Min       1Q   Median       3Q      Max
-19.2683  -8.8875  -0.5952   8.0360  22.1088

Coefficients:
                     Estimate Std. Error t value Pr(>|t|)
(Intercept)             59.64      15.47   3.856 0.000365 ***
pupil_textbook_ratio   -20.13      15.89  -1.267 0.211635
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 10.17 on 45 degrees of freedom
Multiple R-squared:  0.03445,	Adjusted R-squared:  0.01299
F-statistic: 1.606 on 1 and 45 DF,  p-value: 0.2116

# What do we learn from above regression?

This runs dropout rate (Y) against the pupil textbook ratio (x). <br />
The p-value is high. Therefore, we can conclude that the explanatory variable does not affect the dependent variable in a statistically significant way. That is, the pupil textbook ratio does not affect the dropout rates in a statistically significant way<br />

#### Access to education rates

In [84]:
%%R 
# guide for linear regression
model <- lm(never_been_to_school_or_learning_institution_pct ~ pupil_textbook_ratio, df_kenya_education_no_total_r)
summary(model)

Call:
lm(formula = never_been_to_school_or_learning_institution_pct ~
    pupil_textbook_ratio, data = df_kenya_education_no_total_r)

Residuals:
    Min      1Q  Median      3Q     Max
-15.924 -12.057  -8.707   1.926  54.093

Coefficients:
                     Estimate Std. Error t value Pr(>|t|)
(Intercept)            -14.18      30.94  -0.458    0.649
pupil_textbook_ratio    35.29      31.78   1.110    0.273

Residual standard error: 20.34 on 45 degrees of freedom
Multiple R-squared:  0.02666,	Adjusted R-squared:  0.005034
F-statistic: 1.233 on 1 and 45 DF,  p-value: 0.2728

# What do we learn from above regression?

This runs access to education rate (Y) against the pupil textbook ratio (x). <br />
The p-value is high. Therefore, we can conclude that the explanatory variable does not affect the dependent variable in a statistically significant way. That is, the pupil textbook ratio does not affect the access to education rates in a statistically significant way<br />

#### Math scores

In [110]:
%%R 
# guide for linear regression
model <- lm(mathematics_mean ~ pupil_textbook_ratio, df_kenya_education_no_total_r)
summary(model)

Call:
lm(formula = mathematics_mean ~ pupil_textbook_ratio, data = df_kenya_education_no_total_r)

Residuals:
     Min       1Q   Median       3Q      Max
-103.624  -24.680   -9.081   23.083  131.966

Coefficients:
                     Estimate Std. Error t value Pr(>|t|)
(Intercept)            442.15      70.23   6.296 1.13e-07 ***
pupil_textbook_ratio    59.67      72.15   0.827    0.413
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 46.17 on 45 degrees of freedom
Multiple R-squared:  0.01497,	Adjusted R-squared:  -0.006916
F-statistic: 0.6841 on 1 and 45 DF,  p-value: 0.4126

# What do we learn from above regression?

This runs mathematics scores (Y) against the pupil textbook ratio (x). <br />
The p-value is high. Therefore, we can conclude that the explanatory variable does not affect the dependent variable in a statistically significant way. That is, the pupil textbook ratio does not affect the math scores in a statistically significant way<br />

# Electricity (X5)

#### Dropout rates

In [85]:
%%R 
# guide for linear regression
model <- lm(left_school_over_left_before_and_after_as_pct ~ no_power_pct, df_kenya_education_no_total_r)
summary(model)

Call:
lm(formula = left_school_over_left_before_and_after_as_pct ~
    no_power_pct, data = df_kenya_education_no_total_r)

Residuals:
     Min       1Q   Median       3Q      Max
-19.3294  -9.0958   0.5388   7.5827  20.6818

Coefficients:
             Estimate Std. Error t value Pr(>|t|)
(Intercept)  40.17934    1.82293  22.041   <2e-16 ***
no_power_pct -0.01983    0.38524  -0.051    0.959
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 10.35 on 45 degrees of freedom
Multiple R-squared:  5.888e-05,	Adjusted R-squared:  -0.02216
F-statistic: 0.00265 on 1 and 45 DF,  p-value: 0.9592

# What do we learn from above regression?

This runs dropout rate (Y) against access to electricity (x). <br />
The p-value is high. Therefore, we can conclude that the explanatory variable does not affect the dependent variable in a statistically significant way. That is, access to electricity does not affect the dropout rates in a statistically significant way<br />

#### Access to Education rates

In [86]:
%%R 
# guide for linear regression
model <- lm(never_been_to_school_or_learning_institution_pct ~ no_power_pct, df_kenya_education_no_total_r)
summary(model)

Call:
lm(formula = never_been_to_school_or_learning_institution_pct ~
    no_power_pct, data = df_kenya_education_no_total_r)

Residuals:
    Min      1Q  Median      3Q     Max
-14.266  -8.533  -4.025  -1.251  59.916

Coefficients:
             Estimate Std. Error t value Pr(>|t|)
(Intercept)   11.3246     2.8029   4.040 0.000206 ***
no_power_pct   3.2732     0.5923   5.526 1.57e-06 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 15.91 on 45 degrees of freedom
Multiple R-squared:  0.4042,	Adjusted R-squared:  0.391
F-statistic: 30.53 on 1 and 45 DF,  p-value: 1.57e-06

# What do we learn from above regression?

This runs access to education rate (Y) against access to electricity (x). <br />
The p-value is low. Therefore, we can conclude that the explanatory variable affects the dependent variable in a statistically significant way. That is, access to electricity affects access to education rates in a statistically significant way<br />
The multiple r-squared value is 40%, meaning 40% of the variance in access to education can be explained by access to electricity

#### Math scores

In [111]:
%%R 
# guide for linear regression
model <- lm(mathematics_mean ~ no_power_pct, df_kenya_education_no_total_r)
summary(model)

Call:
lm(formula = mathematics_mean ~ no_power_pct, data = df_kenya_education_no_total_r)

Residuals:
     Min       1Q   Median       3Q      Max
-104.578  -24.391   -9.872   24.169  128.137

Coefficients:
             Estimate Std. Error t value Pr(>|t|)
(Intercept)   505.130      8.079  62.520   <2e-16 ***
no_power_pct   -1.944      1.707  -1.139    0.261
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 45.86 on 45 degrees of freedom
Multiple R-squared:  0.02801,	Adjusted R-squared:  0.006411
F-statistic: 1.297 on 1 and 45 DF,  p-value: 0.2608

# What do we learn from above regression?

This runs mathematics scores (Y) against access to electricity (x). <br />
The p-value is high. Therefore, we can conclude that the explanatory variable does not affect the dependent variable in a statistically significant way. That is, access to electricity does not affect the math scores in a statistically significant way<br />

# Digital Devices (X6)

#### Dropout rates

In [87]:
%%R 
# guide for linear regression
model <- lm(left_school_over_left_before_and_after_as_pct ~ pct_installed, df_kenya_education_no_total_r)
summary(model)

Call:
lm(formula = left_school_over_left_before_and_after_as_pct ~
    pct_installed, data = df_kenya_education_no_total_r)

Residuals:
     Min       1Q   Median       3Q      Max
-19.5381  -6.5678  -0.0363   7.7892  19.8489

Coefficients:
              Estimate Std. Error t value Pr(>|t|)
(Intercept)     2.4378    31.1699   0.078    0.938
pct_installed   0.3832     0.3165   1.211    0.232

Residual standard error: 10.18 on 45 degrees of freedom
Multiple R-squared:  0.03154,	Adjusted R-squared:  0.01002
F-statistic: 1.465 on 1 and 45 DF,  p-value: 0.2324

# What do we learn from above regression?

This runs dropout rate (Y) against access to digital devices (x). <br />
The p-value is high. Therefore, we can conclude that the explanatory variable does not affect the dependent variable in a statistically significant way. That is, access to digital devices does not affect the dropout rates in a statistically significant way<br />

#### Access to education rates

In [88]:
%%R 
# guide for linear regression
model <- lm(never_been_to_school_or_learning_institution_pct ~ pct_installed, df_kenya_education_no_total_r)
summary(model)

Call:
lm(formula = never_been_to_school_or_learning_institution_pct ~
    pct_installed, data = df_kenya_education_no_total_r)

Residuals:
    Min      1Q  Median      3Q     Max
-26.087  -9.825  -7.482   0.443  59.775

Coefficients:
              Estimate Std. Error t value Pr(>|t|)
(Intercept)   175.2730    58.6853   2.987  0.00455 **
pct_installed  -1.5785     0.5959  -2.649  0.01110 *
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 19.17 on 45 degrees of freedom
Multiple R-squared:  0.1349,	Adjusted R-squared:  0.1156
F-statistic: 7.016 on 1 and 45 DF,  p-value: 0.0111

# What do we learn from above regression?

This runs access to education rate (Y) against access to a complete set of digital devices (x). <br />
The p-value is low. Therefore, we can conclude that the explanatory variable affects the dependent variable in a statistically significant way. That is, access to a complete set of digital devicess affects access to education rates in a statistically significant way<br />
The multiple r-squared value is 13%, meaning 13% of the variance in access to education can be explained by access to electricity

#### Math scores

In [112]:
%%R 
# guide for linear regression
model <- lm(mathematics_mean ~ pct_installed, df_kenya_education_no_total_r)
summary(model)

Call:
lm(formula = mathematics_mean ~ pct_installed, data = df_kenya_education_no_total_r)

Residuals:
   Min     1Q Median     3Q    Max
-96.61 -27.85 -11.66  26.22 131.28

Coefficients:
              Estimate Std. Error t value Pr(>|t|)
(Intercept)    386.977    141.382   2.737  0.00884 **
pct_installed    1.149      1.436   0.800  0.42785
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 46.19 on 45 degrees of freedom
Multiple R-squared:  0.01403,	Adjusted R-squared:  -0.007884
F-statistic: 0.6402 on 1 and 45 DF,  p-value: 0.4278

# What do we learn from above regression?

This runs math scores (Y) against access to digital devices (x). <br />
The p-value is high. Therefore, we can conclude that the explanatory variable does not affect the dependent variable in a statistically significant way. That is, access to digital devices does not affect the math scores in a statistically significant way<br />

# Private Public Dichotomy (X7)

#### Dropout rates

In [89]:
%%R 
# guide for linear regression
model <- lm(left_school_over_left_before_and_after_as_pct ~ public_over_overall_enrolment_as_pct, df_kenya_education_no_total_r)
summary(model)

Call:
lm(formula = left_school_over_left_before_and_after_as_pct ~
    public_over_overall_enrolment_as_pct, data = df_kenya_education_no_total_r)

Residuals:
     Min       1Q   Median       3Q      Max
-17.5851  -5.7137   0.3488   7.5389  15.8606

Coefficients:
                                     Estimate Std. Error t value Pr(>|t|)
(Intercept)                           -7.3613    10.6351  -0.692    0.492
public_over_overall_enrolment_as_pct   0.5641     0.1254   4.497 4.81e-05 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 8.595 on 45 degrees of freedom
Multiple R-squared:   0.31,	Adjusted R-squared:  0.2947
F-statistic: 20.22 on 1 and 45 DF,  p-value: 4.813e-05

# What do we learn from above regression?

This runs dropout rate (Y) against the rate of enrolment in public school (x). <br />
The p-value is low. Therefore, we can conclude that the explanatory variable affects the dependent variable in a statistically significant way. That is, enrolment in public school vs private school affects dropout rates in a statistically significant way<br />
The multiple r-squared value is 31%, meaning 31% of the variance in dropout rates can be explained by rates of enrolment in public school

#### Access to education rates

In [90]:
%%R 
# guide for linear regression
model <- lm(never_been_to_school_or_learning_institution_pct ~ public_over_overall_enrolment_as_pct, df_kenya_education_no_total_r)
summary(model)

Call:
lm(formula = never_been_to_school_or_learning_institution_pct ~
    public_over_overall_enrolment_as_pct, data = df_kenya_education_no_total_r)

Residuals:
    Min      1Q  Median      3Q     Max
-14.563 -11.825  -9.915   1.582  57.193

Coefficients:
                                     Estimate Std. Error t value Pr(>|t|)
(Intercept)                           10.2026    25.4621   0.401    0.691
public_over_overall_enrolment_as_pct   0.1165     0.3003   0.388    0.700

Residual standard error: 20.58 on 45 degrees of freedom
Multiple R-squared:  0.003333,	Adjusted R-squared:  -0.01882
F-statistic: 0.1505 on 1 and 45 DF,  p-value: 0.6999

# What do we learn from above regression?

This runs access to education rate (Y) against public school enrolment rates (x). <br />
The p-value is high. Therefore, we can conclude that the explanatory variable does not affect the dependent variable in a statistically significant way. That is, public school enrolment ratesdoes not affect the access to education rates in a statistically significant way<br />

#### Math scores

In [113]:
%%R 
# guide for linear regression
model <- lm(mathematics_mean ~ public_over_overall_enrolment_as_pct, df_kenya_education_no_total_r)
summary(model)

Call:
lm(formula = mathematics_mean ~ public_over_overall_enrolment_as_pct,
    data = df_kenya_education_no_total_r)

Residuals:
     Min       1Q   Median       3Q      Max
-135.260  -24.483   -0.991   23.612  119.917

Coefficients:
                                     Estimate Std. Error t value Pr(>|t|)
(Intercept)                          663.9187    52.0287  12.761  < 2e-16 ***
public_over_overall_enrolment_as_pct  -1.9474     0.6137  -3.173  0.00272 **
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 42.05 on 45 degrees of freedom
Multiple R-squared:  0.1829,	Adjusted R-squared:  0.1647
F-statistic: 10.07 on 1 and 45 DF,  p-value: 0.002717

# What do we learn from above regression?

This runs math scores (Y) against the rate of enrolment in public school (x). <br />
The p-value is low. Therefore, we can conclude that the explanatory variable affects the dependent variable in a statistically significant way. That is, enrolment in public school vs private school affects math scores in a statistically significant way<br />
The multiple r-squared value is 18%, meaning 18% of the variance in math scores can be explained by rates of enrolment in public school

# The question of school density

How do I check for whether distance to school affects education outcomes?<br />
There is no straightforward way in this moment. <br />
I could work with number of schools over area. <br />
But on a practical level that would not be properly accurate since some areas are less dense. <br />
So I need a parameter that I: <br />
    1) Should consider an estimate <br />
    2) Should count in number of schools, area and population of the county: <br />
   > Population per number of schools will give me number of people served per school. If I divide this by area, I can get number of people served per school per area. It is not perfect but it could be something to work with. <br />
 Another question: Wouldn't a multiple regression do this on my behalf without my input?

# School Density (X8)

In [104]:
#### Dropout rates

# %%R 
# # guide for linear regression
# model <- lm(left_school_over_left_before_and_after_as_pct ~ population_per_no_of_schools_over_area, df_kenya_education_no_total_r)
# summary(model)

In [101]:
%%R 
# guide for linear regression
school_density_variable<-(df_kenya_education_no_total_r$population/df_kenya_education_no_total_r$number_of_schools)/df_kenya_education_no_total_r$land_area_km_sq
model <- lm(left_school_over_left_before_and_after_as_pct ~ school_density_variable, df_kenya_education_no_total_r)
summary(model)

Call:
lm(formula = left_school_over_left_before_and_after_as_pct ~
    school_density_variable, data = df_kenya_education_no_total_r)

Residuals:
    Min      1Q  Median      3Q     Max
-20.821  -8.308  -0.082   8.377  22.102

Coefficients:
                        Estimate Std. Error t value Pr(>|t|)
(Intercept)               37.922      2.285   16.60   <2e-16 ***
school_density_variable    5.865      4.846    1.21    0.233
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 10.25 on 44 degrees of freedom
  (1 observation deleted due to missingness)
Multiple R-squared:  0.03222,	Adjusted R-squared:  0.01022
F-statistic: 1.465 on 1 and 44 DF,  p-value: 0.2326

# What do we learn from above regression?

This runs dropout rate (Y) against a variable of school density (x). <br />
The p-value is high. Therefore, we can conclude that the explanatory variable does not affect the dependent variable in a statistically significant way. That is, school density does not affect the dropout rates in a statistically significant way<br />

#### Access to education rates

In [100]:
%%R 
# guide for linear regression
school_density_variable<-(df_kenya_education_no_total_r$population/df_kenya_education_no_total_r$number_of_schools)/df_kenya_education_no_total_r$land_area_km_sq

model <- lm(never_been_to_school_or_learning_institution_pct ~ school_density_variable, df_kenya_education_no_total_r)
summary(model)

Call:
lm(formula = never_been_to_school_or_learning_institution_pct ~
    school_density_variable, data = df_kenya_education_no_total_r)

Residuals:
    Min      1Q  Median      3Q     Max
-21.081 -11.334  -5.512   8.424  46.259

Coefficients:
                        Estimate Std. Error t value Pr(>|t|)
(Intercept)               32.505      3.919   8.293 1.54e-10 ***
school_density_variable  -34.779      8.313  -4.184 0.000135 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 17.59 on 44 degrees of freedom
  (1 observation deleted due to missingness)
Multiple R-squared:  0.2846,	Adjusted R-squared:  0.2683
F-statistic:  17.5 on 1 and 44 DF,  p-value: 0.0001348

# What do we learn from above regression?

This runs access to education rates (Y) against a variable of school density normalised over population, area and number of schools (x). <br />
The p-value is low. Therefore, we can conclude that the explanatory variable affects the dependent variable in a statistically significant way. That is, school density affects access to education rates in a statistically significant way<br />
The multiple r-squared value is 28%, meaning 28% of the variance in access to education rates can be explained by rates of enrolment in public school

In [ ]:
#### Math scores

In [194]:
%%R 
# guide for linear regression
school_density_variable<-(df_kenya_education_no_total_r$population/df_kenya_education_no_total_r$number_of_schools)/df_kenya_education_no_total_r$land_area_km_sq

model <- lm(mathematics_mean ~ school_density_variable, df_kenya_education_no_total_r)
summary(model)

Call:
lm(formula = mathematics_mean ~ school_density_variable, data = df_kenya_education_no_total_r)

Residuals:
    Min      1Q  Median      3Q     Max
-95.900 -25.020  -9.137  24.088 127.208

Coefficients:
                        Estimate Std. Error t value Pr(>|t|)
(Intercept)               492.95      10.37  47.518   <2e-16 ***
school_density_variable    18.59      22.00   0.845    0.403
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 46.56 on 44 degrees of freedom
  (1 observation deleted due to missingness)
Multiple R-squared:  0.01597,	Adjusted R-squared:  -0.006395
F-statistic: 0.7141 on 1 and 44 DF,  p-value: 0.4027

# What do we learn from above regression?

This runs math scores (Y) against a variable of school density (x). <br />
The p-value is high. Therefore, we can conclude that the explanatory variable does not affect the dependent variable in a statistically significant way. That is, school density does not affect the mathematics scores in a statistically significant way<br />

# For multivariable regressions:
1) For dropout rates (left_school_over_left_before_and_after_as_pct)
2) For access to education rates (never_been_to_school_or_learning_institution_pct)
3) For math scores (mathematics_mean)

#### Here is a list of the X variables titles and column names for reference:
1) County Government revenues (total_revenue_2021_22_plus)
2) Average school size (average_school_size)
3) Pupil Teacher ratio (overall_pri_ptr_PTR)
4) Pupil textbook ratio (pupil_textbook_ratio)
5) Electricity (no_power_pct)
6) Digital Devices (pct_installed)
7) Private/ public dichotomy (public_over_overall_enrolment_as_pct)
8) School density normalised by population, number of schools, and area (school_density_variable)

## For Dropout rates

In [115]:
# ### Every variable
# %%R 
# # guide for multivariable regression
# model <- lm(left_school_over_left_before_and_after_as_pct ~ total_revenue_2021_22_plus + average_school_size + overall_pri_ptr_PTR + pupil_textbook_ratio + no_power_pct + pct_installed + public_over_overall_enrolment_as_pct + school_density_variable, df_kenya_education_no_total_r)
# summary(model)

In [193]:
%%R 
# guide for multivariable regression
model <- lm(left_school_over_left_before_and_after_as_pct ~total_revenue_2021_22_plus + average_school_size+ pupil_textbook_ratio  + public_over_overall_enrolment_as_pct+ school_density_variable, df_kenya_education_no_total_r)
summary(model)

Call:
lm(formula = left_school_over_left_before_and_after_as_pct ~
    total_revenue_2021_22_plus + average_school_size + pupil_textbook_ratio +
        public_over_overall_enrolment_as_pct + school_density_variable,
    data = df_kenya_education_no_total_r)

Residuals:
     Min       1Q   Median       3Q      Max
-15.4850  -5.5526   0.1198   5.3399  18.5502

Coefficients:
                                       Estimate Std. Error t value Pr(>|t|)
(Intercept)                           3.422e-01  1.764e+01   0.019 0.984625
total_revenue_2021_22_plus           -4.106e-04  2.932e-04  -1.401 0.169060
average_school_size                   3.834e-02  2.098e-02   1.827 0.075158 .
pupil_textbook_ratio                 -1.349e+01  1.245e+01  -1.084 0.285044
public_over_overall_enrolment_as_pct  5.135e-01  1.438e-01   3.572 0.000941 ***
school_density_variable               5.437e+00  4.486e+00   1.212 0.232667
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 7.825 on 40 degrees of freedom
  (1 observation deleted due to missingness)
Multiple R-squared:  0.4877,	Adjusted R-squared:  0.4237
F-statistic: 7.616 on 5 and 40 DF,  p-value: 4.189e-05

### For dropout rates, 42% was nearly the highest adjusted r-squared value I could get above. The p values are however quite high

# For Access to Education Rates

In [117]:
# ### Every variable
# %%R 
# # guide for multivariable regression
# model <- lm(never_been_to_school_or_learning_institution_pct ~ total_revenue_2021_22_plus + average_school_size + overall_pri_ptr_PTR + pupil_textbook_ratio + no_power_pct + pct_installed + public_over_overall_enrolment_as_pct + school_density_variable, df_kenya_education_no_total_r)
# summary(model)

In [191]:
%%R 
# guide for multivariable regression
model <- lm(never_been_to_school_or_learning_institution_pct ~ total_revenue_2021_22_plus + average_school_size + overall_pri_ptr_PTR + pct_installed + public_over_overall_enrolment_as_pct + school_density_variable + with_national_grid_pct, df_kenya_education_no_total_r)
summary(model)

Call:
lm(formula = never_been_to_school_or_learning_institution_pct ~
    total_revenue_2021_22_plus + average_school_size + overall_pri_ptr_PTR +
        pct_installed + public_over_overall_enrolment_as_pct +
        school_density_variable + with_national_grid_pct, data = df_kenya_education_no_total_r)

Residuals:
     Min       1Q   Median       3Q      Max
-19.3877  -2.6088  -0.4802   2.6778  25.4374

Coefficients:
                                       Estimate Std. Error t value Pr(>|t|)
(Intercept)                          79.1896421 31.1164260   2.545 0.015232 *
total_revenue_2021_22_plus           -0.0008881  0.0006918  -1.284 0.207201
average_school_size                  -0.0513338  0.0354854  -1.447 0.156423
overall_pri_ptr_PTR                   1.0640865  0.3119358   3.411 0.001578 **
pct_installed                        -0.1041078  0.3492883  -0.298 0.767327
public_over_overall_enrolment_as_pct -0.3846339  0.1770304  -2.173 0.036281 *
school_density_variable              -2.4487005  6.7029457  -0.365 0.716955
with_national_grid_pct               -0.3693169  0.0955961  -3.863 0.000435 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 8.851 on 37 degrees of freedom
  (2 observations deleted due to missingness)
Multiple R-squared:  0.8457,	Adjusted R-squared:  0.8165
F-statistic: 28.97 on 7 and 37 DF,  p-value: 3.601e-13

In [222]:
%%R 
# guide for multivariable regression
model <- lm(never_been_to_school_or_learning_institution_pct ~total_revenue_2021_22_plus + log(average_school_size) + log(overall_pri_ptr_PTR) + public_over_overall_enrolment_as_pct + with_national_grid_pct, df_kenya_education_no_total_r)
summary(model)

Call:
lm(formula = never_been_to_school_or_learning_institution_pct ~
    total_revenue_2021_22_plus + log(average_school_size) + log(overall_pri_ptr_PTR) +
        public_over_overall_enrolment_as_pct + with_national_grid_pct,
    data = df_kenya_education_no_total_r)

Residuals:
     Min       1Q   Median       3Q      Max
-20.0151  -2.0431   0.1631   3.3804  22.0823

Coefficients:
                                       Estimate Std. Error t value Pr(>|t|)
(Intercept)                           7.097e+01  3.514e+01   2.020 0.050143 .
total_revenue_2021_22_plus           -8.507e-04  5.623e-04  -1.513 0.138167
log(average_school_size)             -2.508e+01  1.075e+01  -2.334 0.024706 *
log(overall_pri_ptr_PTR)              4.559e+01  1.223e+01   3.727 0.000598 ***
public_over_overall_enrolment_as_pct -3.753e-01  1.517e-01  -2.474 0.017710 *
with_national_grid_pct               -3.736e-01  7.490e-02  -4.989 1.23e-05 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 8.459 on 40 degrees of freedom
  (1 observation deleted due to missingness)
Multiple R-squared:  0.8484,	Adjusted R-squared:  0.8294
F-statistic: 44.77 on 5 and 40 DF,  p-value: 2.399e-15

### For access to education rates, 82% was the highest adjusted r-squared value I could get above. 
The p values are all low except for revenue. <br />
Even during the one by one linear regressions, access to education rates also had teh lowest p values. <br />

# For Mathematics Scores

In [223]:
# ### Every variable
# %%R 
# # guide for multivariable regression
# model <- lm(mathematics_mean ~ total_revenue_2021_22_plus + average_school_size + overall_pri_ptr_PTR + pupil_textbook_ratio + no_power_pct + pct_installed + public_over_overall_enrolment_as_pct + school_density_variable, df_kenya_education_no_total_r)
# summary(model)

In [233]:
%%R 
# guide for multivariable regression
model <- lm(mathematics_mean ~ total_revenue_2021_22_plus + public_over_overall_enrolment_as_pct, df_kenya_education_no_total_r)
summary(model)

Call:
lm(formula = mathematics_mean ~ total_revenue_2021_22_plus +
    public_over_overall_enrolment_as_pct, data = df_kenya_education_no_total_r)

Residuals:
     Min       1Q   Median       3Q      Max
-126.818  -25.311   -2.709   28.732  129.060

Coefficients:
                                       Estimate Std. Error t value Pr(>|t|)
(Intercept)                          610.507159  65.276220   9.353 5.05e-12 ***
total_revenue_2021_22_plus             0.001741   0.001304   1.335   0.1887
public_over_overall_enrolment_as_pct  -1.518272   0.688095  -2.206   0.0326 *
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 41.69 on 44 degrees of freedom
Multiple R-squared:  0.2147,	Adjusted R-squared:  0.179
F-statistic: 6.014 on 2 and 44 DF,  p-value: 0.004911

### For math scores, 17% was the highest adjusted r-squared value I could get above. 
This signifies that conceptualising a different model with different variables would be ideal for predicting math scores