# Setting Everything Up

In [2]:
import pandas as pd
from datetime import datetime

In [3]:
#import the file from the web
import requests
from bs4 import BeautifulSoup
import pandas as pd
from unicodedata import normalize
import re
from datetime import datetime
from pandas import read_csv 
from sklearn.feature_extraction.text import CountVectorizer
import json
from flatten_json import flatten


# I can give a number or use None to remove maximum ceiling & display all columns
pd.options.display.max_columns = None

# # I want to be able to see the entire narrative, so remove the maximum width for each column
# pd.options.display.max_colwidth = None

# pd.options.display.float_format = '{:,.0f}'.format

import string

%matplotlib inline

In [4]:
%load_ext rpy2.ipython
%load_ext autoreload
%autoreload 2

%matplotlib inline  
from matplotlib import rcParams
rcParams['figure.figsize'] = (8, 8)

import warnings
from rpy2.rinterface import RRuntimeWarning
warnings.filterwarnings("ignore") # Ignore all warnings
# warnings.filterwarnings("ignore", category=RRuntimeWarning) # Show some warnings

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import display, HTML

In [5]:
%%javascript
// Disable auto-scrolling
IPython.OutputArea.prototype._should_scroll = function(lines) {
    return false;
}

In [6]:
%%R

# My commonly used R imports

require('tidyverse')

R[write to console]: Loading required package: tidyverse

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.2     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ ggplot2   3.4.2     ✔ tibble    3.2.1
✔ lubridate 1.9.2     ✔ tidyr     1.3.0
✔ purrr     1.0.1
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

In [7]:
#To Download PDFs
from urllib.parse import urljoin

In [8]:
#To import camelot and PDF-related items
import camelot
import ghostscript
import sys

In [9]:
%%R

library(jpeg)
library(wordcloud)
library(RColorBrewer)
library(wordcloud2)
library(tm)

R[write to console]: Loading required package: RColorBrewer

R[write to console]: Loading required package: NLP

R[write to console]:
Attaching package: ‘NLP’


R[write to console]: The following object is masked from ‘package:ggplot2’:

    annotate

In [10]:
from sklearn.feature_extraction.text import CountVectorizer

In [11]:
%%R
library(vistime)
library(shiny)
library(plotly)
#for timeline plotting

R[write to console]:
Attaching package: ‘plotly’


R[write to console]: The following object is masked from ‘package:ggplot2’:

    last_plot


R[write to console]: The following object is masked from ‘package:stats’:

    filter


R[write to console]: The following object is masked from ‘package:graphics’:

    layout

In [12]:
from collections import Counter

# Reading the Data

In [34]:
df_edu_lighting_fuel=pd.read_csv("edu_lighting_fuel.csv")
df_edu_piped=pd.read_csv("edu_piped.csv")
df_edu_internet=pd.read_csv("edu_internet.csv")
df_edu_mobile_phone=pd.read_csv("edu_mobile_phone.csv")

# Merging the data

In [35]:
import pandas as pd

# Assuming you have the four datasets: df_edu_lighting_fuel, df_edu_piped, df_edu_internet, df_edu_mobile_phone

# Merge the datasets one by one using the 'County_slash_Sub_County' column
merged_df = df_edu_lighting_fuel.merge(df_edu_piped, on='County_slash_Sub_County', how='inner')
merged_df = merged_df.merge(df_edu_internet, on='County_slash_Sub_County', how='inner')
merged_df = merged_df.merge(df_edu_mobile_phone, on='County_slash_Sub_County', how='inner')

# Exclude columns where 'County_slash_Sub_County' value contains 'KENYA FOREST'
merged_df = merged_df.loc[~merged_df['County_slash_Sub_County'].str.contains('KENYA FOREST')]

# Print the resulting merged DataFrame
merged_df

,County_slash_Sub_County,lighting_Conventional_Households,lighting_Mains_Electricity,lighting_Paraffin_Pressure_lamp,lighting_Paraffin_Lantern,lighting_Paraffin_Tin_Lamp,lighting_Gas_Lamp,lighting_Wood,lighting_Solar_and_Solar_Torch_and_Battery_Torch,lighting_Solar,lighting_Torch_slash_Spotlight_Solar_Charged,lighting_Torch_slash_Spotlight_Dry_cells,lighting_Candle,lighting_Battery_Car_Slash_Charged,lighting_Generator_Diesel_slash_Petrol),lighting_Biogas,lighting_Not_Stated,drinking_water_Conventional_Households,drinking_water_Pond,drinking_water_Dam_slash_Lake,drinking_water_Stream_slash_River,drinking_water_Protected_Spring,drinking_water_Unprotected_Spring,drinking_water_Protected_Well,unprotected_well_borehole_piped_dwelling,drinking_water_Unprotected_Well,drinking_water_Borehole_slash_Tube_well,drinking_water_Piped_into_dwelling,drinking_water_Piped_to_yard_slash_plot,drinking_water_Bottled_water,drinking_water_Rain_slash_Harvested_water,drinking_water_Water_Vendor,drinking_water_Public_tap_slash_Standpipe,drinking_water_Not_Stated,internet_population_above3_Total_Male_Female,internet_population_above3_Total,internet_population_above3_Male,internet_population_above3_Female,Use_of_Internet_Total,Use_of_Internet_pct,Use_of_Internet_Male_pct,Use_of_Internet_Male,Use_of_Internet_pct.1,Use_of_Internet_Female,Use_of_Internet_pct.2,Use_of_Desktop_Computer_slash_Laptop_slash_Tablet_Total,pct_male_pct_female_pct,Use_of_Desktop_Computer_slash_Laptop_slash_Tablet_Total_pct,Use_of_Desktop_Computer_slash_Laptop_slash_Tablet_Male,Use_of_Desktop_Computer_slash_Laptop_slash_Tablet_Male_pct,Use_of_Desktop_Computer_slash_Laptop_slash_Tablet_Female,Use_of_Desktop_Computer_slash_Laptop_slash_Tablet_Female_pct,mo_phone_population_above_3_Total_Male_Female,mo_phone_population_above_3_Total,mo_phone_population_above_3_Male,mo_phone_population_above_3_Female,mobile_phone_Total,mobile_phone_Total_pct,mobile_phone_Male_and_pct,mobile_phone_Male,mobile_phone_Male_pct,mobile_phone_Female,mobile_phone_Female_pct
0,MOMBASA,"376,295",85.9,0.5,2.7,6.3,0.1,0,1.5 0.4 0.3,NaN,NaN,NaN,2.2,0.1,0,0,0,"376,295",0.1,0.2,0.1,1.2,0.1,4.6,0.4 5.2 7.2,NaN,NaN,NaN,5.2,11.4,0.3,43.5,20.5,0,"1,100,173 552,476 547,681",NaN,NaN,NaN,"431,327",39.2,"232,526 42.1",NaN,NaN,"198,792",36.3,"184,713","16.8 104,805 19.0 79,904",NaN,NaN,NaN,NaN,14.6,"1,100,173 552,476 547,681",NaN,NaN,NaN,"679,402",61.8,"353,192 63.9",NaN,NaN,"326,200",59.6
1,CHANGAMWE,"46,439",87.7,0.4,3.1,3.6,0,0,0.9 0.6 0.4,NaN,NaN,NaN,3.2,0.1,0,0,0,"46,439",0,0,0.1,0.8,0.1,1.2,0.1 1.2 4.0,NaN,NaN,NaN,4.2,5.2,0.1,59.9,23.3,0,"121,334 63,184 58,150",NaN,NaN,NaN,"48,368",39.9,"27,252 43.1",NaN,NaN,"21,116",36.3,"18,986","15.6 11,455 18.1 7,531",NaN,NaN,NaN,NaN,13.0,"121,334 63,184 58,150",NaN,NaN,NaN,"79,248",65.3,"42,684 67.6",NaN,NaN,"36,564",62.9
2,JOMVU,"53,214",81,0.4,3.7,9.5,0.1,0.1,2.1 0.6 0.3,NaN,NaN,NaN,2.1,0.1,-,0,0,"53,214",0.1,0.1,0.1,0.8,0.2,1.5,0.4 1.1 5.2,NaN,NaN,NaN,4.3,4.7,0.2,53.4,27.8,0,"149,699 75,931 73,765",NaN,NaN,NaN,"48,246",32.2,"27,583 36.3",NaN,NaN,"20,662",28.0,"19,386","12.9 11,739 15.5 7,646",NaN,NaN,NaN,NaN,10.4,"149,699 75,931 73,765",NaN,NaN,NaN,"88,469",59.1,"46,928 61.8",NaN,NaN,"41,539",56.3
3,KISAUNI,"88,159",82.8,0.4,2.9,7.9,0.1,0.1,3.1 0.4 0.2,NaN,NaN,NaN,1.9,0.1,0,0,0,"88,159",0.2,0.3,0.2,2.2,0.1,4,0.8 8.2 11.8,NaN,NaN,NaN,9.2,10.5,0.3,21.6,30.7,0,"263,742 131,351 132,388",NaN,NaN,NaN,"93,781",35.6,"50,503 38.4",NaN,NaN,"43,275",32.7,"40,374","15.3 22,737 17.3 17,636",NaN,NaN,NaN,NaN,13.3,"263,742 131,351 132,388",NaN,NaN,NaN,"154,731",58.7,"80,185 61.0",NaN,NaN,"74,544",56.3
4,LIKONI,"80,002",87.2,0.7,2.4,6.4,0.1,0,1.0 0.3 0.2,NaN,NaN,NaN,1.7,0.1,-,0,0,"80,002",0.1,0.3,0.2,0.7,0.4,11.6,0.5 6.7 4.1,NaN,NaN,NaN,2.4,4.9,0.5,60.7,7,0,"228,472 115,784 112,685",NaN,NaN,NaN,"75,298",33.0,"43,018 37.2",NaN,NaN,"32,279",28.6,"27,252","11.9 16,461 14.2 10,791",NaN,NaN,NaN,NaN,9.6,"228,472 115,784 112,685",NaN,NaN,NaN,"134,590",58.9,"72,030 62.2",NaN,NaN,"62,559",55.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
894,MAKADARA,"70,080",95.3,0.2,1.2,0.9,0,0,0.1 0.1 0.1,NaN,NaN,NaN,2,0,-,-,0,"70,080",0,0.2,0.1,0.1,0.1,0.1,0.1 0.5 18.8,NaN,NaN,NaN,21.6,3.3,0.2,28.1,27,0,"176,283 89,283 86,991",NaN,NaN,NaN,"92,196",52.3,"49,033 54.9",NaN,NaN,"43,160",49.6,"47,544","27.0 26,262 29.4 21,280",NaN,NaN,NaN,NaN,24.5,"176,283 89,283 86,991",NaN,NaN,NaN,"126,251",71.6,"64,996 72.8",NaN,NaN,"61,248",70.4
895,MATHARE,"74,967",95.3,0.2,0.8,1.6,0,0,0.1 0.1 0.1,NaN,NaN,NaN,1.8,0,0,0,0.1,"74,967",0,0,0,0.3,0,0.1,0.0 0.3 10.1,NaN,NaN,NaN,41.9,0.8,0.1,19.3,27,0.1,"188,625 97,147 91,465",NaN,NaN,NaN,"70,295",37.3,"41,412 42.6",NaN,NaN,"28,877",31.6,"23,989","12.7 14,838 15.3 9,147",NaN,NaN,NaN,NaN,10.0,"188,625 97,147 91,465",NaN,NaN,NaN,"122,056",64.7,"65,520 67.4",NaN,NaN,"56,524",61.8
896,NJIRU,"204,492",96.9,0.1,0.7,0.4,0.1,0,0.4 0.1 0.1,NaN,NaN,NaN,1.1,0,0,0,0.1,"204,492",0,0.1,0,0.4,0,0.3,0.0 5.6 21.8,NaN,NaN,NaN,39.8,5.3,1.8,14.6,10.2,0.1,"573,474 280,310 293,137",NaN,NaN,NaN,"269,869",47.1,"139,682 49.8",NaN,NaN,"130,174",44.4,"128,093","22.3 70,897 25.3 57,190",NaN,NaN,NaN,NaN,19.5,"573,474 280,310 293,137",NaN,NaN,NaN,"377,259",65.8,"185,710 66.3",NaN,NaN,"191,531",65.3
897,STAREHE,"66,108",97,0.1,0.5,0.7,0,0,0.1 0.1 0.1,NaN,NaN,NaN,1.3,0,-,-,0.1,"66,108",0,0.2,0,0.5,0,0.2,0.0 2.3 27.4,NaN,NaN,NaN,23.8,9.2,0.1,10,26.1,0.1,"182,149 90,480 91,660",NaN,NaN,NaN,"107,513",59.0,"55,484 61.3",NaN,NaN,"52,021",56.8,"59,704","32.8 32,417 35.8 27,282",NaN,NaN,NaN,NaN,29.8,"182,149 90,480 91,660",NaN,NaN,NaN,"131,259",72.1,"65,980 72.9",NaN,NaN,"65,270",71.2
898,WESTLANDS,"103,489",97.1,0.1,0.6,0.7,0,0,0.3 0.1 0.1,NaN,NaN,NaN,0.9,0,0,0,0,"103,489",0,0.2,0.1,1.1,0,0.3,0.0 2.5 25.5,NaN,NaN,NaN,28.3,15.6,0.1,6.4,19.8,0,"283,907 140,701 143,192",NaN,NaN,NaN,"180,776",63.7,"92,596 65.8",NaN,NaN,"88,170",61.6,"123,623","43.5 64,123 45.6 59,493",NaN,NaN,NaN,NaN,41.5,"283,907 140,701 143,192",NaN,NaN,NaN,"214,876",75.7,"107,491 76.4",NaN,NaN,"107,374",75.0

In [36]:
merged_df.to_csv("all_counties.csv")

# Separating the Data

In [37]:
merged_df

,County_slash_Sub_County,lighting_Conventional_Households,lighting_Mains_Electricity,lighting_Paraffin_Pressure_lamp,lighting_Paraffin_Lantern,lighting_Paraffin_Tin_Lamp,lighting_Gas_Lamp,lighting_Wood,lighting_Solar_and_Solar_Torch_and_Battery_Torch,lighting_Solar,lighting_Torch_slash_Spotlight_Solar_Charged,lighting_Torch_slash_Spotlight_Dry_cells,lighting_Candle,lighting_Battery_Car_Slash_Charged,lighting_Generator_Diesel_slash_Petrol),lighting_Biogas,lighting_Not_Stated,drinking_water_Conventional_Households,drinking_water_Pond,drinking_water_Dam_slash_Lake,drinking_water_Stream_slash_River,drinking_water_Protected_Spring,drinking_water_Unprotected_Spring,drinking_water_Protected_Well,unprotected_well_borehole_piped_dwelling,drinking_water_Unprotected_Well,drinking_water_Borehole_slash_Tube_well,drinking_water_Piped_into_dwelling,drinking_water_Piped_to_yard_slash_plot,drinking_water_Bottled_water,drinking_water_Rain_slash_Harvested_water,drinking_water_Water_Vendor,drinking_water_Public_tap_slash_Standpipe,drinking_water_Not_Stated,internet_population_above3_Total_Male_Female,internet_population_above3_Total,internet_population_above3_Male,internet_population_above3_Female,Use_of_Internet_Total,Use_of_Internet_pct,Use_of_Internet_Male_pct,Use_of_Internet_Male,Use_of_Internet_pct.1,Use_of_Internet_Female,Use_of_Internet_pct.2,Use_of_Desktop_Computer_slash_Laptop_slash_Tablet_Total,pct_male_pct_female_pct,Use_of_Desktop_Computer_slash_Laptop_slash_Tablet_Total_pct,Use_of_Desktop_Computer_slash_Laptop_slash_Tablet_Male,Use_of_Desktop_Computer_slash_Laptop_slash_Tablet_Male_pct,Use_of_Desktop_Computer_slash_Laptop_slash_Tablet_Female,Use_of_Desktop_Computer_slash_Laptop_slash_Tablet_Female_pct,mo_phone_population_above_3_Total_Male_Female,mo_phone_population_above_3_Total,mo_phone_population_above_3_Male,mo_phone_population_above_3_Female,mobile_phone_Total,mobile_phone_Total_pct,mobile_phone_Male_and_pct,mobile_phone_Male,mobile_phone_Male_pct,mobile_phone_Female,mobile_phone_Female_pct
0,MOMBASA,"376,295",85.9,0.5,2.7,6.3,0.1,0,1.5 0.4 0.3,NaN,NaN,NaN,2.2,0.1,0,0,0,"376,295",0.1,0.2,0.1,1.2,0.1,4.6,0.4 5.2 7.2,NaN,NaN,NaN,5.2,11.4,0.3,43.5,20.5,0,"1,100,173 552,476 547,681",NaN,NaN,NaN,"431,327",39.2,"232,526 42.1",NaN,NaN,"198,792",36.3,"184,713","16.8 104,805 19.0 79,904",NaN,NaN,NaN,NaN,14.6,"1,100,173 552,476 547,681",NaN,NaN,NaN,"679,402",61.8,"353,192 63.9",NaN,NaN,"326,200",59.6
1,CHANGAMWE,"46,439",87.7,0.4,3.1,3.6,0,0,0.9 0.6 0.4,NaN,NaN,NaN,3.2,0.1,0,0,0,"46,439",0,0,0.1,0.8,0.1,1.2,0.1 1.2 4.0,NaN,NaN,NaN,4.2,5.2,0.1,59.9,23.3,0,"121,334 63,184 58,150",NaN,NaN,NaN,"48,368",39.9,"27,252 43.1",NaN,NaN,"21,116",36.3,"18,986","15.6 11,455 18.1 7,531",NaN,NaN,NaN,NaN,13.0,"121,334 63,184 58,150",NaN,NaN,NaN,"79,248",65.3,"42,684 67.6",NaN,NaN,"36,564",62.9
2,JOMVU,"53,214",81,0.4,3.7,9.5,0.1,0.1,2.1 0.6 0.3,NaN,NaN,NaN,2.1,0.1,-,0,0,"53,214",0.1,0.1,0.1,0.8,0.2,1.5,0.4 1.1 5.2,NaN,NaN,NaN,4.3,4.7,0.2,53.4,27.8,0,"149,699 75,931 73,765",NaN,NaN,NaN,"48,246",32.2,"27,583 36.3",NaN,NaN,"20,662",28.0,"19,386","12.9 11,739 15.5 7,646",NaN,NaN,NaN,NaN,10.4,"149,699 75,931 73,765",NaN,NaN,NaN,"88,469",59.1,"46,928 61.8",NaN,NaN,"41,539",56.3
3,KISAUNI,"88,159",82.8,0.4,2.9,7.9,0.1,0.1,3.1 0.4 0.2,NaN,NaN,NaN,1.9,0.1,0,0,0,"88,159",0.2,0.3,0.2,2.2,0.1,4,0.8 8.2 11.8,NaN,NaN,NaN,9.2,10.5,0.3,21.6,30.7,0,"263,742 131,351 132,388",NaN,NaN,NaN,"93,781",35.6,"50,503 38.4",NaN,NaN,"43,275",32.7,"40,374","15.3 22,737 17.3 17,636",NaN,NaN,NaN,NaN,13.3,"263,742 131,351 132,388",NaN,NaN,NaN,"154,731",58.7,"80,185 61.0",NaN,NaN,"74,544",56.3
4,LIKONI,"80,002",87.2,0.7,2.4,6.4,0.1,0,1.0 0.3 0.2,NaN,NaN,NaN,1.7,0.1,-,0,0,"80,002",0.1,0.3,0.2,0.7,0.4,11.6,0.5 6.7 4.1,NaN,NaN,NaN,2.4,4.9,0.5,60.7,7,0,"228,472 115,784 112,685",NaN,NaN,NaN,"75,298",33.0,"43,018 37.2",NaN,NaN,"32,279",28.6,"27,252","11.9 16,461 14.2 10,791",NaN,NaN,NaN,NaN,9.6,"228,472 115,784 112,685",NaN,NaN,NaN,"134,590",58.9,"72,030 62.2",NaN,NaN,"62,559",55.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
894,MAKADARA,"70,080",95.3,0.2,1.2,0.9,0,0,0.1 0.1 0.1,NaN,NaN,NaN,2,0,-,-,0,"70,080",0,0.2,0.1,0.1,0.1,0.1,0.1 0.5 18.8,NaN,NaN,NaN,21.6,3.3,0.2,28.1,27,0,"176,283 89,283 86,991",NaN,NaN,NaN,"92,196",52.3,"49,033 54.9",NaN,NaN,"43,160",49.6,"47,544","27.0 26,262 29.4 21,280",NaN,NaN,NaN,NaN,24.5,"176,283 89,283 86,991",NaN,NaN,NaN,"126,251",71.6,"64,996 72.8",NaN,NaN,"61,248",70.4
895,MATHARE,"74,967",95.3,0.2,0.8,1.6,0,0,0.1 0.1 0.1,NaN,NaN,NaN,1.8,0,0,0,0.1,"74,967",0,0,0,0.3,0,0.1,0.0 0.3 10.1,NaN,NaN,NaN,41.9,0.8,0.1,19.3,27,0.1,"188,625 97,147 91,465",NaN,NaN,NaN,"70,295",37.3,"41,412 42.6",NaN,NaN,"28,877",31.6,"23,989","12.7 14,838 15.3 9,147",NaN,NaN,NaN,NaN,10.0,"188,625 97,147 91,465",NaN,NaN,NaN,"122,056",64.7,"65,520 67.4",NaN,NaN,"56,524",61.8
896,NJIRU,"204,492",96.9,0.1,0.7,0.4,0.1,0,0.4 0.1 0.1,NaN,NaN,NaN,1.1,0,0,0,0.1,"204,492",0,0.1,0,0.4,0,0.3,0.0 5.6 21.8,NaN,NaN,NaN,39.8,5.3,1.8,14.6,10.2,0.1,"573,474 280,310 293,137",NaN,NaN,NaN,"269,869",47.1,"139,682 49.8",NaN,NaN,"130,174",44.4,"128,093","22.3 70,897 25.3 57,190",NaN,NaN,NaN,NaN,19.5,"573,474 280,310 293,137",NaN,NaN,NaN,"377,259",65.8,"185,710 66.3",NaN,NaN,"191,531",65.3
897,STAREHE,"66,108",97,0.1,0.5,0.7,0,0,0.1 0.1 0.1,NaN,NaN,NaN,1.3,0,-,-,0.1,"66,108",0,0.2,0,0.5,0,0.2,0.0 2.3 27.4,NaN,NaN,NaN,23.8,9.2,0.1,10,26.1,0.1,"182,149 90,480 91,660",NaN,NaN,NaN,"107,513",59.0,"55,484 61.3",NaN,NaN,"52,021",56.8,"59,704","32.8 32,417 35.8 27,282",NaN,NaN,NaN,NaN,29.8,"182,149 90,480 91,660",NaN,NaN,NaN,"131,259",72.1,"65,980 72.9",NaN,NaN,"65,270",71.2
898,WESTLANDS,"103,489",97.1,0.1,0.6,0.7,0,0,0.3 0.1 0.1,NaN,NaN,NaN,0.9,0,0,0,0,"103,489",0,0.2,0.1,1.1,0,0.3,0.0 2.5 25.5,NaN,NaN,NaN,28.3,15.6,0.1,6.4,19.8,0,"283,907 140,701 143,192",NaN,NaN,NaN,"180,776",63.7,"92,596 65.8",NaN,NaN,"88,170",61.6,"123,623","43.5 64,123 45.6 59,493",NaN,NaN,NaN,NaN,41.5,"283,907 140,701 143,192",NaN,NaN,NaN,"214,876",75.7,"107,491 76.4",NaN,NaN,"107,374",75.0

In [38]:
import pandas as pd

# Assuming you have the merged DataFrame called merged_df

# Split the values in "lighting_Solar_and_Solar_Torch_and_Battery_Torch" column
split_values = merged_df["lighting_Solar_and_Solar_Torch_and_Battery_Torch"].str.split(" ", expand=True)
merged_df["lighting_Solar"] = split_values[0]
merged_df["lighting_Torch_slash_Spotlight_Solar_Charged"] = split_values[1]
merged_df["lighting_Torch_slash_Spotlight_Dry_cells"] = split_values[2]

# Split the values in "unprotected_well_borehole_piped_dwelling" column
split_values = merged_df["unprotected_well_borehole_piped_dwelling"].str.split(" ", expand=True)
merged_df["drinking_water_Unprotected_Well"] = split_values[0]
merged_df["drinking_water_Borehole_slash_Tube_well"] = split_values[1]
merged_df["drinking_water_Piped_into_dwelling"] = split_values[2]

# Split the values in "internet_population_above3_Total_Male_Female" column
split_values = merged_df["internet_population_above3_Total_Male_Female"].str.split(" ", expand=True)
merged_df["internet_population_above3_Total"] = split_values[0]
merged_df["internet_population_above3_Male"] = split_values[1]
merged_df["internet_population_above3_Female"] = split_values[2]

# Split the values in "Use_of_Internet_Male_pct" column
split_values = merged_df["Use_of_Internet_Male_pct"].str.split(" ", expand=True)
merged_df["Use_of_Internet_Male"] = split_values[0]
merged_df["Use_of_Internet_pct.1"] = split_values[1]

# Split the values in "pct_male_pct_female_pct" column
split_values = merged_df["pct_male_pct_female_pct"].str.split(" ", expand=True)
merged_df["Use_of_Desktop_Computer_slash_Laptop_slash_Tablet_Total_pct"] = split_values[0]
merged_df["Use_of_Desktop_Computer_slash_Laptop_slash_Tablet_Male"] = split_values[1]
merged_df["Use_of_Desktop_Computer_slash_Laptop_slash_Tablet_Male_pct"] = split_values[2]
merged_df["Use_of_Desktop_Computer_slash_Laptop_slash_Tablet_Female"] = split_values[3]

# Split the values in "mo_phone_population_above_3_Total_Male_Female" column
split_values = merged_df["mo_phone_population_above_3_Total_Male_Female"].str.split(" ", expand=True)
merged_df["mo_phone_population_above_3_Total"] = split_values[0]
merged_df["mo_phone_population_above_3_Male"] = split_values[1]
merged_df["mo_phone_population_above_3_Female"] = split_values[2]

# Split the values in "mobile_phone_Male_and_pct" column
split_values = merged_df["mobile_phone_Male_and_pct"].str.split(" ", expand=True)
merged_df["mobile_phone_Male"] = split_values[0]
merged_df["mobile_phone_Male_pct"] = split_values[1]

In [39]:
merged_df

,County_slash_Sub_County,lighting_Conventional_Households,lighting_Mains_Electricity,lighting_Paraffin_Pressure_lamp,lighting_Paraffin_Lantern,lighting_Paraffin_Tin_Lamp,lighting_Gas_Lamp,lighting_Wood,lighting_Solar_and_Solar_Torch_and_Battery_Torch,lighting_Solar,lighting_Torch_slash_Spotlight_Solar_Charged,lighting_Torch_slash_Spotlight_Dry_cells,lighting_Candle,lighting_Battery_Car_Slash_Charged,lighting_Generator_Diesel_slash_Petrol),lighting_Biogas,lighting_Not_Stated,drinking_water_Conventional_Households,drinking_water_Pond,drinking_water_Dam_slash_Lake,drinking_water_Stream_slash_River,drinking_water_Protected_Spring,drinking_water_Unprotected_Spring,drinking_water_Protected_Well,unprotected_well_borehole_piped_dwelling,drinking_water_Unprotected_Well,drinking_water_Borehole_slash_Tube_well,drinking_water_Piped_into_dwelling,drinking_water_Piped_to_yard_slash_plot,drinking_water_Bottled_water,drinking_water_Rain_slash_Harvested_water,drinking_water_Water_Vendor,drinking_water_Public_tap_slash_Standpipe,drinking_water_Not_Stated,internet_population_above3_Total_Male_Female,internet_population_above3_Total,internet_population_above3_Male,internet_population_above3_Female,Use_of_Internet_Total,Use_of_Internet_pct,Use_of_Internet_Male_pct,Use_of_Internet_Male,Use_of_Internet_pct.1,Use_of_Internet_Female,Use_of_Internet_pct.2,Use_of_Desktop_Computer_slash_Laptop_slash_Tablet_Total,pct_male_pct_female_pct,Use_of_Desktop_Computer_slash_Laptop_slash_Tablet_Total_pct,Use_of_Desktop_Computer_slash_Laptop_slash_Tablet_Male,Use_of_Desktop_Computer_slash_Laptop_slash_Tablet_Male_pct,Use_of_Desktop_Computer_slash_Laptop_slash_Tablet_Female,Use_of_Desktop_Computer_slash_Laptop_slash_Tablet_Female_pct,mo_phone_population_above_3_Total_Male_Female,mo_phone_population_above_3_Total,mo_phone_population_above_3_Male,mo_phone_population_above_3_Female,mobile_phone_Total,mobile_phone_Total_pct,mobile_phone_Male_and_pct,mobile_phone_Male,mobile_phone_Male_pct,mobile_phone_Female,mobile_phone_Female_pct
0,MOMBASA,"376,295",85.9,0.5,2.7,6.3,0.1,0,1.5 0.4 0.3,1.5,0.4,0.3,2.2,0.1,0,0,0,"376,295",0.1,0.2,0.1,1.2,0.1,4.6,0.4 5.2 7.2,0.4,5.2,7.2,5.2,11.4,0.3,43.5,20.5,0,"1,100,173 552,476 547,681","1,100,173","552,476","547,681","431,327",39.2,"232,526 42.1","232,526",42.1,"198,792",36.3,"184,713","16.8 104,805 19.0 79,904",16.8,"104,805",19.0,"79,904",14.6,"1,100,173 552,476 547,681","1,100,173","552,476","547,681","679,402",61.8,"353,192 63.9","353,192",63.9,"326,200",59.6
1,CHANGAMWE,"46,439",87.7,0.4,3.1,3.6,0,0,0.9 0.6 0.4,0.9,0.6,0.4,3.2,0.1,0,0,0,"46,439",0,0,0.1,0.8,0.1,1.2,0.1 1.2 4.0,0.1,1.2,4.0,4.2,5.2,0.1,59.9,23.3,0,"121,334 63,184 58,150","121,334","63,184","58,150","48,368",39.9,"27,252 43.1","27,252",43.1,"21,116",36.3,"18,986","15.6 11,455 18.1 7,531",15.6,"11,455",18.1,"7,531",13.0,"121,334 63,184 58,150","121,334","63,184","58,150","79,248",65.3,"42,684 67.6","42,684",67.6,"36,564",62.9
2,JOMVU,"53,214",81,0.4,3.7,9.5,0.1,0.1,2.1 0.6 0.3,2.1,0.6,0.3,2.1,0.1,-,0,0,"53,214",0.1,0.1,0.1,0.8,0.2,1.5,0.4 1.1 5.2,0.4,1.1,5.2,4.3,4.7,0.2,53.4,27.8,0,"149,699 75,931 73,765","149,699","75,931","73,765","48,246",32.2,"27,583 36.3","27,583",36.3,"20,662",28.0,"19,386","12.9 11,739 15.5 7,646",12.9,"11,739",15.5,"7,646",10.4,"149,699 75,931 73,765","149,699","75,931","73,765","88,469",59.1,"46,928 61.8","46,928",61.8,"41,539",56.3
3,KISAUNI,"88,159",82.8,0.4,2.9,7.9,0.1,0.1,3.1 0.4 0.2,3.1,0.4,0.2,1.9,0.1,0,0,0,"88,159",0.2,0.3,0.2,2.2,0.1,4,0.8 8.2 11.8,0.8,8.2,11.8,9.2,10.5,0.3,21.6,30.7,0,"263,742 131,351 132,388","263,742","131,351","132,388","93,781",35.6,"50,503 38.4","50,503",38.4,"43,275",32.7,"40,374","15.3 22,737 17.3 17,636",15.3,"22,737",17.3,"17,636",13.3,"263,742 131,351 132,388","263,742","131,351","132,388","154,731",58.7,"80,185 61.0","80,185",61.0,"74,544",56.3
4,LIKONI,"80,002",87.2,0.7,2.4,6.4,0.1,0,1.0 0.3 0.2,1.0,0.3,0.2,1.7,0.1,-,0,0,"80,002",0.1,0.3,0.2,0.7,0.4,11.6,0.5 6.7 4.1,0.5,6.7,4.1,2.4,4.9,0.5,60.7,7,0,"228,472 115,784 112,685","228,472","115,784","112,685","75,298",33.0,"43,018 37.2","43,018",37.2,"32,279",28.6,"27,252","11.9 16,461 14.2 10,791",11.9,"16,461",14.2,"10,791",9.6,"228,472 115,784 112,685","228,472","115,784","112,685","134,590",58.9,"72,030 62.2","72,030",62.2,"62,559",55.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
894,MAKADARA,"70,080",95.3,0.2,1.2,0.9,0,0,0.1 0.1 0.1,0.1,0.1,0.1,2,0,-,-,0,"70,080",0,0.2,0.1,0.1,0.1,0.1,0.1 0.5 18.8,0.1,0.5,18.8,21.6,3.3,0.2,28.1,27,0,"176,283 89,283 86,991","176,283","89,283","86,991","92,196",52.3,"49,033 54.9","49,033",54.9,"43,160",49.6,"47,544","27.0 26,262 29.4 21,280",27.0,"26,262",29.4,"21,280",24.5,"176,283 89,283 86,991","176,283","89,283","86,991","126,251",71.6,"64,996 72.8","64,996",72.8,"61,248",70.4
895,MATHARE,"74,967",95.3,0.2,0.8,1.6,0,0,0.1 0.1 0.1,0.1,0.1,0.1,1.8,0,0,0,0.1,"74,967",0,0,0,0.3,0,0.1,0.0 0.3 10.1,0.0,0.3,10.1,41.9,0.8,0.1,19.3,27,0.1,"188,625 97,147 91,465","188,625","97,147","91,465","70,295",37.3,"41,412 42.6","41,412",42.6,"28,877",31.6,"23,989","12.7 14,838 15.3 9,147",12.7,"14,838",15.3,"9,147",10.0,"188,625 97,147 91,465","188,625","97,147","91,465","122,056",64.7,"65,520 67.4","65,520",67.4,"56,524",61.8
896,NJIRU,"204,492",96.9,0.1,0.7,0.4,0.1,0,0.4 0.1 0.1,0.4,0.1,0.1,1.1,0,0,0,0.1,"204,492",0,0.1,0,0.4,0,0.3,0.0 5.6 21.8,0.0,5.6,21.8,39.8,5.3,1.8,14.6,10.2,0.1,"573,474 280,310 293,137","573,474","280,310","293,137","269,869",47.1,"139,682 49.8","139,682",49.8,"130,174",44.4,"128,093","22.3 70,897 25.3 57,190",22.3,"70,897",25.3,"57,190",19.5,"573,474 280,310 293,137","573,474","280,310","293,137","377,259",65.8,"185,710 66.3","185,710",66.3,"191,531",65.3
897,STAREHE,"66,108",97,0.1,0.5,0.7,0,0,0.1 0.1 0.1,0.1,0.1,0.1,1.3,0,-,-,0.1,"66,108",0,0.2,0,0.5,0,0.2,0.0 2.3 27.4,0.0,2.3,27.4,23.8,9.2,0.1,10,26.1,0.1,"182,149 90,480 91,660","182,149","90,480","91,660","107,513",59.0,"55,484 61.3","55,484",61.3,"52,021",56.8,"59,704","32.8 32,417 35.8 27,282",32.8,"32,417",35.8,"27,282",29.8,"182,149 90,480 91,660","182,149","90,480","91,660","131,259",72.1,"65,980 72.9","65,980",72.9,"65,270",71.2
898,WESTLANDS,"103,489",97.1,0.1,0.6,0.7,0,0,0.3 0.1 0.1,0.3,0.1,0.1,0.9,0,0,0,0,"103,489",0,0.2,0.1,1.1,0,0.3,0.0 2.5 25.5,0.0,2.5,25.5,28.3,15.6,0.1,6.4,19.8,0,"283,907 140,701 143,192","283,907","140,701","143,192","180,776",63.7,"92,596 65.8","92,596",65.8,"88,170",61.6,"123,623","43.5 64,123 45.6 59,493",43.5,"64,123",45.6,"59,493",41.5,"283,907 140,701 143,192","283,907","140,701","143,192","214,876",75.7,"107,491 76.4","107,491",76.4,"107,374",75.0

In [40]:
import pandas as pd

# Assuming you have the merged DataFrame called merged_df

# Split the values in "lighting_Solar_and_Solar_Torch_and_Battery_Torch" column
lighting_split = merged_df["lighting_Solar_and_Solar_Torch_and_Battery_Torch"].str.split(" ", expand=True)
merged_df["lighting_Solar"] = lighting_split[0]
merged_df["lighting_Torch_slash_Spotlight_Solar_Charged"] = lighting_split[1]
merged_df["lighting_Torch_slash_Spotlight_Dry_cells"] = lighting_split[2]

# Split the values in "unprotected_well_borehole_piped_dwelling" column
water_split = merged_df["unprotected_well_borehole_piped_dwelling"].str.split(" ", expand=True)
merged_df["drinking_water_Unprotected_Well"] = water_split[0]
merged_df["drinking_water_Borehole_slash_Tube_well"] = water_split[1]
merged_df["drinking_water_Piped_into_dwelling"] = water_split[2]

# Split the values in "internet_population_above3_Total_Male_Female" column
internet_split = merged_df["internet_population_above3_Total_Male_Female"].str.split(" ", expand=True)
merged_df["internet_population_above3_Total"] = internet_split[0]
merged_df["internet_population_above3_Male"] = internet_split[1]
merged_df["internet_population_above3_Female"] = internet_split[2]

# Split the values in "Use_of_Internet_Male_pct" column
internet_usage_split = merged_df["Use_of_Internet_Male_pct"].str.split(" ", expand=True)
merged_df["Use_of_Internet_Male"] = internet_usage_split[0]
merged_df["Use_of_Internet_pct.1"] = internet_usage_split[1]

# Split the values in "pct_male_pct_female_pct" column
computer_usage_split = merged_df["pct_male_pct_female_pct"].str.split(" ", expand=True)
merged_df["Use_of_Desktop_Computer_slash_Laptop_slash_Tablet_Total_pct"] = computer_usage_split[0]
merged_df["Use_of_Desktop_Computer_slash_Laptop_slash_Tablet_Male"] = computer_usage_split[1]
merged_df["Use_of_Desktop_Computer_slash_Laptop_slash_Tablet_Male_pct"] = computer_usage_split[2]
merged_df["Use_of_Desktop_Computer_slash_Laptop_slash_Tablet_Female"] = computer_usage_split[3]

# Split the values in "mo_phone_population_above_3_Total_Male_Female" column
mobile_split = merged_df["mo_phone_population_above_3_Total_Male_Female"].str.split(" ", expand=True)
merged_df["mo_phone_population_above_3_Total"] = mobile_split[0]
merged_df["mo_phone_population_above_3_Male"] = mobile_split[1]
merged_df["mo_phone_population_above_3_Female"] = mobile_split[2]

# Split the values in "mobile_phone_Male_and_pct" column
mobile_usage_split = merged_df["mobile_phone_Male_and_pct"].str.split(" ", expand=True)
merged_df["mobile_phone_Male"] = mobile_usage_split[0]
merged_df["mobile_phone_Male_pct"] = mobile_usage_split[1]

In [42]:
merged_df.to_csv("secondary_income_data.csv")